### PR TITLE
Bfix: Fixes domain(port) in configFile ( Fixes #565 )

### LINKED ISSUE #565: Bug: Incorrect domain port in configFile.json
`"domain": "http://localhost:3001"` --> `"domain": "http://localhost:3000"`
Since the site is opened on port 3000, the domain name should be put accordingly. 
Therefore port should be changed to 3000.

### PR DESCRIPTION
**Pull request by sopu**
Fixes #565

### CODE REVIEW

**Comment by sudheesh001** [comment]
@sopu We are not sure if this is what is needed, Are you using `oauth-proxy` in a seperate screen session ?

**Comment by sopu** [comment]
@sudheesh001: When I tried opening the twitter wall on localhost:3000, " 'Access-Control-Allow-Origin' value does not match" error popped up which AFAIU is due to the domain name specified in the config file. 
Changing the domain name worked for me.
PS: In dev mode.

**Comment by sopu** [comment]
@sudheesh001 Suggestions??

**Comment by sudheesh001** [comment]
@aneeshd16 Can you review this please, it seems to be breaking for me.

**Comment by aneeshd16** [comment]
@sopu gulp uses `custom_configFile.json` to load these settings. My `custom_configFile.json` has `http://localhost:3000` as the domain. This should be good to merge. @sudheesh001 dunno how this can break things. Can you please recheck?

**Pull request merged**
