### PR TITLE
Feature/wall #36 #34 #32

### PR DESCRIPTION
**Pull request by julianfox**
A first release for the wall features

### CODE REVIEW

**Comment by julianfox** [comment]
It's not finish:
TODO:
The first status have to use a full size image 400x400
The wall title have to be different if the search is about a # 
The left side have to be displayed with Loklak logo and the statistics widget
I have a issue about the timeline (sometime a old status is front to new status)

QUESTIONS:
In start, do we display all old status ? or do we start just with the next new one ?

**Comment by Orbiter** [comment]
Hi, just push your stuff into the repository yourself, I do not have the time to test that and will merge your code anyway :) I know thats not along the 'project managemet line' but currently we should build our app on responsibility, professionality and trust!

**Comment by Orbiter** [comment]
ARGS, now everything is fucked up. I got a lot of error messages. I obviously have to install angular-animate, therefore I did:
```
sudo npm install -g bower
bower install --save angular-animate
```
but then
```
loklak_webclient admin$ npm install
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN locking Error: EACCES, open '/Users/admin/.npm/_locks/angular-animate-0e143c8a818f5c8a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/admin/.npm/_locks/angular-animate-0e143c8a818f5c8a.lock failed { [Error: EACCES, open '/Users/admin/.npm/_locks/angular-animate-0e143c8a818f5c8a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/admin/.npm/_locks/angular-animate-0e143c8a818f5c8a.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
```
wtf?

**Comment by julianfox** [comment]
You have just to do npm install for update the dependency
You don't have to install or use bower

I hope that fix your issue ?

**Comment by julianfox** [comment]
May be you can try with sudo: sudo npm install ?

**Comment by julianfox** [comment]
May be this can help also: https://github.com/npm/npm/issues/7407

**Comment by Orbiter** [comment]
well now almost all error messages have disappeared, but when I run 'gulp dev' the following line appears:
```
Note: The code generator has deoptimised the styling of "/Users/admin/git/loklak_webclient/bower_components/angular/angular.js" as it exceeds the max of "100KB".
```
.. and the browser shows an empty page

**Comment by julianfox** [comment]
I did again npm install and gulp dev... and i don't have it... i am looking for solution

**Comment by julianfox** [comment]
Can you try to remove the bower_components folder ? we don't use bower.

**Comment by Orbiter** [comment]
I removed it, run "sudo npm install" (without sudo I get errors) and the result is the same...

**Comment by julianfox** [comment]
Very weird, do you have exactly the same message:
Note: The code generator has deoptimised the styling of "/Users/admin/git/loklak_webclient/bower_components/angular/angular.js" as it exceeds the max of "100KB". ?

**Comment by Orbiter** [comment]
yes I have exactly that message as well

**Comment by sudheesh001** [comment]
I am unable to reproduce this, everything seems to be working perfectly for me here.

**Comment by Orbiter** [comment]
:relaxed:
I solved this by deletion of all node and npm config files and reinstalling everything.

Looks good, thank you!

**Comment by julianfox** [comment]
Ok, i think it was a conflict with Bower an another package manager.

**Pull request merged**
