### PR TITLE
Integrated #11 to #9,

### PR DESCRIPTION
**Pull request by fuksi**
This is a major pull request.

In order to use only query (the server denied 2 consecutive queries from one host), I have integrated
 ```eval``` controllers, views into ```statistics```'s, involving a major restructure of ```statistics.js```, however the old code didn't change much.

A live version can be tested at: http://gofullstack.me:3001/statistics 
and it is responsive.

### CODE REVIEW

**Comment by Orbiter** [comment]
wow, this looks really good. Just merge it (there are conflicts, I would not know what to do)
Great work!

**Comment by aneeshd16** [comment]
Looks awesome. The merge conflicts are very slight, minimum change to statistics.js, and some cosmetic changes to statistics.html

**Comment by aneeshd16** [comment]
@fuksi I am getting this error when i run `gulp dev`
    stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid top-level expression

**Comment by aneeshd16** [comment]
Never mind, there was some corrupted text in main.scss, fixed it.

**Comment by fuksi** [comment]
Yeap, I'm working on this, there was 3 commits on master ahead of me when i try to merge, most of them were about styling. This can help

http://stackoverflow.com/questions/24620629/gulp-sass-error-unhandled-stream-error-in-pipe

**Comment by fuksi** [comment]
Oh, oh okey, @aneeshd16 can you push the fixed one to master (no need for pull request). Thanks a lot!

**Comment by aneeshd16** [comment]
Sure. Done. :+1:

**Comment by Orbiter** [comment]
```
gulp dev
[22:50:58] Using gulpfile ~/git/loklak_webclient/gulpfile.js
[22:50:58] Starting 'clean'...
[22:50:58] Finished 'clean' after 8.69 ms
[22:50:58] Starting 'dev'...
[22:50:58] Starting 'styles'...
[22:50:58] Starting 'minify-css'...
[22:50:58] Starting 'images'...
[22:50:58] Starting 'fonts'...
[22:50:58] Starting 'views'...
[22:50:58] Starting 'browserify'...
[22:50:58] Rebundle...
[22:50:59] Finished 'images' after 55 ms
[22:50:59] Finished 'minify-css' after 130 ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid top-level expression
```

**Comment by aneeshd16** [comment]
@Orbiter fixed here 45163f44f733d20b04717739dc26d3519722b805

**Comment by Orbiter** [comment]
phantastic! works!
now... can we save a little bit of vertical space, otherwise the whole page does not fit on the screen and a screen copy is not possible. Maybe only as much as one horizontal bar (but don't remove that).

one more thing: the three stat columns do not have the same width. Can they have the same width?

**Pull request merged**
