### PR TITLE
Auth enhancements

### PR DESCRIPTION
**Pull request by aneeshd16**
With each request, a httpInterceptor adds the access_token and
screen_name in the header. This allows us to separate authentication
from data methods.

### CODE REVIEW

**Comment by fuksi** [comment]
- I lost old walls, and not able to create a new one. After I try to create, it opens a new tab but the url is like this `http://localhost:3000/thienphucstuff/wall/undefined`
- You might want to add one more case in this incase data is not available, line 71, api.js
`if (data && data.oauth_token === params.token && data.oauth_token_secret === params.secret) {`

**Comment by aneeshd16** [comment]
Try logging out and logging in again. Also check if loklak_server has your access tokens. localhost:9000/api/account.json?screen_name=< username >

**Comment by mariobehling** [comment]
@aneeshd16 What is the status?

**Comment by fuksi** [comment]
@aneeshd16 okay, I tested on another machine and it works. It might be just my server cache that the account creds are not there :) Let's merge this.

**Pull request merged**
