### PR TITLE
Dev home embed

### PR DESCRIPTION
**Pull request by fuksi**
- [x] Solve #432: To test, logout, start from home page, do a search. Suggestions on top shouldn't appear when results are loaded
- [x] Solve #428: All the links are rendered. I didn't change the style much. Home view's feeds now provide embed contents, but still have its own look.
- [x] Solve #424: Please go through the comment's points quickly https://github.com/loklak/loklak_webclient/issues/424#issuecomment-128931782, except for the location one :)

### CODE REVIEW

**Comment by sudheesh001** [comment]
Point 2 and Point 3 are fine @fuksi I am still able to get suggestions on the top search.

Also After making a search if I move to the home page by clicking on the loklak cow, the search box holds the value of the search previously made. I believe this has to be cleared.

screen shot 2015-08-10 at 9 04 14 am

**Comment by fuksi** [comment]
Can you try again the suggestions thing? It seems to work ok on live: http://gofullstack.me:3001/ Try to do a clean build :). If you type and search really fast, it can flash a bit and then go away, but still in the end, it shouldn't show after a search.

**Comment by sudheesh001** [comment]
Can you please update the server with the latest update on this branch, I fixed the location issue and put it in the branch merge with master. Leaving that, this is good to go. Please update the server and comment again and I'll be more than happy to merge this :+1:

**Comment by fuksi** [comment]
Done. Everything is working on live. Let's merge!

**Pull request merged**
