### PR TITLE
Zoom to load

### LINKED ISSUE #211: send current map display range as search attribute to loklak_server
if the user can see a map from https://github.com/loklak/loklak_webclient/issues/170 then the user probably wants to zoom into the map. Each time the user zooms into the map or changes the view, then another search must be send to loklak_server with the latest boundaries of the visible map area.

The feature https://github.com/loklak/loklak_server/issues/47 now supports this. Instead of sending only a `/location` constraint as addition to the search query, also the boundaries must be submitted using the following schema: `/location=lon-west,lat-south,lon-east,lat-north`

### PR DESCRIPTION
**Pull request by fuksi**
Fix #211. Zoom to an area will show more results (of course if there are any in that area, you can always check in the console for the number of result).  Don't might the missing of search input, it's will be fixed in another UI PR.

To check this locally, you might need to use loklak.org server, for some reason loklak server at localhost is not responding to e.g.  `#london+/location=-99,-52,293,88`.

Link to try quickly: [http://localhost:3000/search?q=%23london%2B%2Fmap](http://localhost:3000/search?q=%23london%2B%2Fmap)

To use loklak.org, change the apiUrl in custom_configFile.json **AND** also remove `settings` task in `gulp/tasks/development.js` temporarily.

### CODE REVIEW

**Comment by prasht63** [comment]
I am getting this error with a blank screen
Uncaught ReferenceError: Invalid left-hand side in assignment

**Comment by prasht63** [comment]
Strangely its working fine now.And I saw some change in results on zooming in and out.However the search box is missing from top nav. @sudheesh001 can you review this please.

**Comment by sudheesh001** [comment]
Reviewing in a few hours.

**Comment by sudheesh001** [comment]
Search box is still missing from top nav, also the top nav doesn't span the whole width of the screen and has a margin present on the `class="container topnav"`

The map functionality so far works and this could be good for merge, the only thing it needs is a change in the top nav bar.

**Comment by mariobehling** [comment]
@sudheesh001 can you make that fix? @fuksi is taking a day off.

**Comment by sudheesh001** [comment]
Resynchronized because, it should be easy to test all the functionality built so far, even though the search box on top nav is removed, its put back there so that the functionality is intact. Enhancements to it can come later.

**Pull request merged**
