### PR TITLE
Fixes #287 , Adds Place as a location source

### LINKED ISSUE #287: Show place name in individual tweet pop-up in case that the place was submitted by twitter
When investigating if the place mapping was done correctly, some tweets can be seen which obviously do not have a place name within their tweet text. Therefore it is not transparent why that tweet appears on that specific location on the map. Therefore place names submitted by twitter is an important context information which should be shown together with the tweet text.

In contrast to the visibility of the place if that was submitted by twitter, the place computed by the loklak_server shall not be shown because this information would already be in the tweet text. Please do:

- when showing a tweet on a map:
 - if (and only if) the field `location_source` contains the exact string `REPORT` then write below the tweet text: 
  - left-aligned a "place mark" (that thing like a upside-down drop)
  - right to the mark the text from the field `place_name`

### PR DESCRIPTION
**Pull request by prasht63**
Details here https://github.com/loklak/loklak_webclient/issues/287#issuecomment-126235305

### CODE REVIEW

**Comment by aneeshd16** [comment]
How do I test this?

**Comment by prasht63** [comment]
In all cases where the location coordinates was created by annotation of the place name given by twitter, the location name should show up on map  search tweet detail box.

**Comment by mariobehling** [comment]
Do you have a screenshot, please? And a link to test this.

**Comment by prasht63** [comment]
Map is not working on my local on any branch.For the time being @aneeshd16 Please follow the steps.
1.While you are in this branch, go to Twitter and post a Tweet with a location name and location set.
2.Try to sreach the Tweet on Loklak Search (map view).
3.You should see the place name in the box

**Comment by aneeshd16** [comment]
For some reason, map search isn't working on my local at all. I just posted a tweet though, if you could post a screenshot of my tweet as it appears on the map, it should be enough to test this PR as I saw that there are not many changes.

**Comment by prasht63** [comment]
I m also facing the same problem. @fuksi can you review please. Thanks!

**Comment by prasht63** [comment]
@fuksi  any update?

**Comment by fuksi** [comment]
This particular marker doesn't make sense. That's not America (the rest of the markers work fine). The code are also okay.

image

**Comment by prasht63** [comment]
@fuksi maybe the user is from USA, thats why Twitter took location as USA.

**Comment by mariobehling** [comment]
@prasht63 If this is identified as USA, then why does not it show up in the US?

**Comment by fuksi** [comment]
The tweet location mark is `(26.87270606048044, -28.10938659012228)` which is in the middle of the ocean. http://loklak.org/api/search.json?timezoneOffset=-180&q=teachable%2C+available%2C+genuine

This is a rare case. I can't say it you'll need to pursuit to fix it or not because I tried all the markers in some tests and this is the only buggy one I found. Please discuss with @Orbiter if this is a matter from the server.

**Comment by prasht63** [comment]
@mariobehling I am not responsible for plotting this on map or aggregating the data which says its in US.This PR was only to add an additional location source.Please look at the code changes.@fuksi please merge if you think its good to go.

**Pull request merged**
