### PR TITLE
Solution for #8. Need help with Angular

### PR DESCRIPTION
**Pull request by fuksi**
#8 Enabling search on init with arbitrary parameters. Also, after a search, path parameters are added, for i.e. sharing links

There is an underlying err that's been bugging me for days. If it's fixed then the UX can be improved a little. You can reproduce the err with 2 consecutive searchs.

screen shot 2015-05-12 at 21 46 56

### CODE REVIEW

**Comment by sudheesh001** [comment]
@fuksi , I've taken the patch file from your commits and applied it, everything seems to be working properly, I don't encounter the Angular errors. Here are the steps I reproduced
1. `gulp dev`
2. `/search?q=fossasia`
3. `/search?q=apple`
4. `/search?q=google`

The only errors I hit are those documented in #42 with random 404's occuring, leaving that everyting seems to be working perfectly with the following combinations of request parameters
`Object {q: "apple", timezoneOffset: undefined}`
`Object {q: "apple", timezoneOffset: "400"}`

Is there anywhere I've gone wrong in reproducing the error ?

**Comment by fuksi** [comment]
@sudheesh001 Sorry I didn't specify clearly on the reproducing part.
The search url works fine. However I added a small feature that, when you search for a term, the url will be updated according to the term (so then we can copy and share the link).  

image  
Can you try to reproduce the error again?  
Thanks!

**Comment by sudheesh001** [comment]
```
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:63
    at Scope.$digest (angular.js:14346)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at angular.js:9798
    at HTMLScriptElement.callback (angular.js:9919)
angular.js:14574 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D
```
Able to reproduce the error.

**Comment by fuksi** [comment]
I'll close this and create a new low priority issue since it's working.

**Pull request closed without merging**
