### PR TITLE
Removed Gulp Prod error

### PR DESCRIPTION
**Pull request by prasht63**
Removed gulp prod error.

### CODE REVIEW

**Comment by aneeshd16** [comment]
@prasht63 , change the last line of your controller to something like this:
`controllersModule.controller('WallDisplay', ['$scope', '$stateParams', '$interval', '$timeout', '$location', '$http', '$window', 'AppSettings', 'SearchService', 'Fullscreen', WallDisplay]);`

You need to explicitly declare all your dependencies.

**Comment by prasht63** [comment]
Made the changes :+1:

**Comment by sudheesh001** [comment]
@prasht63 Still breaking `Uncaught ReferenceError: Invalid left-hand side in assignment`

**Comment by prasht63** [comment]
@sudheesh001 I don't see any error. Can you post a screenshot.And are you sure its due to maps

**Pull request merged**
