### PR TITLE
Query evaluation 

### PR DESCRIPTION
**Pull request by fuksi**
#9. Evaluating functions are currently placed in search controller. These can be put in a separate service if necessary. Results are not ordered, as we can use filters where we see fit. 

For quick tests, evaluated results are output to console. 

If you can, please pull the repo: git clone https://github.com/fuksi/loklak_webclient.git , and test if there are more edge cases.

@aneeshd16 , @sudheesh001

### CODE REVIEW

**Comment by Orbiter** [comment]
I believe
```
-var AppSettings=JSON.parse(fs.readFileSync('custom_configFile.json', 'utf8'));
+var AppSettings=JSON.parse(fs.readFileSync('configFile.json', 'utf8'));
```
will break the current setup again?

**Comment by aneeshd16** [comment]
It wont break the setup per se, but it will defeat the purpose of having a custom settings file, as the configFile.json will get committed everytime.

**Comment by Orbiter** [comment]
We wanted to have a custom settings file to be independent from git settings!

**Comment by fuksi** [comment]
Oh sorry about that, I might got the wrong idea from the last merge, but I do now after reading the new README. I'll change it back!

**Pull request closed without merging**
