### PR TITLE
Wall query fixes

### PR DESCRIPTION
**Pull request by aneeshd16**
see #305 for details. The design is slightly crude, but does the job.
It will get better when #330 is implemented

### CODE REVIEW

**Comment by fuksi** [comment]
The new rules, but should I concern that walls I created are not showing anymore? (You can see I created 2 walls there. I also tried refreshing)
image

**Comment by aneeshd16** [comment]
@fuksi, can you give the steps to reproduce the issue?

**Comment by aneeshd16** [comment]
Don't merge yet, discussion ongoing.

**Comment by fuksi** [comment]
I just created 2 new walls. (there are extra chrome tabs there :)), and go back to see if there are any saved. However it can be my chrome cache. Is it working on your local?

**Comment by aneeshd16** [comment]
yes, it should also be working on test.loklak.net. Could you please check and update?

**Comment by fuksi** [comment]
Checked. It's my cache -_-

**Pull request merged**
