### PR TITLE
Fixes #284. Adds layer for followers and following separately.

### LINKED ISSUE #284: Show followers and following on different Layers on the map.

### PR DESCRIPTION
**Pull request by prasht63**
image

### CODE REVIEW

**Comment by aneeshd16** [comment]
I am getting `Unable to get your followers` and `Unable to get your following` in the console. I am signed in, so I guess this might not be related to rate limiting.
image

**Comment by prasht63** [comment]
It requires some time after signing in to see the followers.Try to sign in through home page and once you are signed in click on the map.

**Comment by mariobehling** [comment]
The question that comes up here as well is: How to deal with people who have thousands, hundreds of thousands and more of followers? Is it possible to display and load them step by step? As discussed saving this kind of data in loklak could also speed up things here. Could you create issues for this, please? This can then be solved in iterative issues.

**Comment by aneeshd16** [comment]
image

Got the following to show up in the map. However, when i clicked on following, nothing happened (yet), and I have no errors in the console.

**Comment by mariobehling** [comment]
@prasht63 My understanding was that you implement checkboxes. Otherwise, how is it possible to show followers and following on one map?

**Comment by prasht63** [comment]
@mariobehling I will implement that.

**Comment by prasht63** [comment]
@aneeshd16 implemented checkbox.Please review

**Comment by mariobehling** [comment]
@prasht63 Please center the map and please get rid of the scroll bar. The map should fit on a normal screen.

Finally have you documented this feature on the Readme.md? Please include the changes in the PR. Thank you.

**Comment by sudheesh001** [comment]
The map is not yet center aligned, this is how it looks for me
screen shot 2015-07-07 at 12 02 03 pm

In the radio options, followers shows up correctly on map with a drop down action of the markers from the top but following throws up an error in console as `"There is error"`

**Comment by aneeshd16** [comment]
Works good now. Can you remove the scroll bar? Use `overflow-y:hidden` on the element.
However, it worked only once, on page refresh I could not see any markers. Don't think it was because of rate limiting because its the first thing i did today. Must have loaded the page only 2-3 times.

**Comment by prasht63** [comment]
@aneeshd16 Thats a separate issue reloading one.Also I am working on scroll.For now when you sign in and then click on map you should see two layers.This PR just centres the map and adds layers.

**Comment by aneeshd16** [comment]
okay cool, that's there. Merging this then.

**Pull request merged**
