### PR TITLE
Dev search v110

### PR DESCRIPTION
**Pull request by fuksi**
**Please do not merge, check only.When everything's ok, I'll go through the conflict (it seems to be a quite simple one)** 
 
Live at http://gofullstack.me:3001/  

- #529 , my search server doesn't have the same search result for that particular tweet ID, but you can always tweet yourself with a facebook link and check.
- #525, please go through the ticks, they're very simple
- https://github.com/loklak/loklak_webclient/issues/491#issuecomment-133578229, please go through the ticks, they're very simple

### CODE REVIEW

**Comment by sudheesh001** [comment]
Looks like the server is down, can you put it back up again for me to test.

**Comment by fuksi** [comment]
It's back on! :)

**Comment by mariobehling** [comment]
* [ ] "Show all" button of followers/following does not work. Best would be if this opens in a tab of the user profile (like at twitter). Maybe this can be included in a future PR.
screenshot from 2015-08-30 16 18 15

**Comment by sudheesh001** [comment]
Looks good, please resolve the conflict and this should be good to go

**Pull request merged**
