### PR TITLE
Oauth proxy fix

### PR DESCRIPTION
**Pull request by aneeshd16**
Solves #302 

How to check:
* Create a few walls
* Sign out
* Sign in

Saved walls should re-appear.

Also squeezed in a design change. Removed the horizontal list, the walls render as thumbnails in 4 columns.

### CODE REVIEW

**Comment by aneeshd16** [comment]
Please close #302 after merge.

**Comment by fuksi** [comment]
In this merge, these options are the same as on live. So which one you have removed? I can't see the option for 4 columns either :)

image

**Comment by aneeshd16** [comment]
On /wall just create a bunch of walls. You'll see that they are shown in a 4 column grid instead of a horizontal list.

**Comment by fuksi** [comment]
Oh that, okay. Merged

**Pull request merged**
