### PR TITLE
Remove unused modules 

### PR DESCRIPTION
**Pull request by prasht63**
gulp prod runs fine locally
image
Fixes Issue #142 partially until we discuss to remove more packages

### CODE REVIEW

**Comment by prasht63** [comment]
yes. Attached the screen grab

**Comment by aneeshd16** [comment]
Errors would only come when you actually use the app. Gulp prod just does minification.

**Comment by prasht63** [comment]
I am using it seeing none :)

On Thu, Jun 11, 2015 at 3:01 PM, Aneesh Devasthale <notifications@github.com

**Comment by aneeshd16** [comment]
Okay, will test and merge then :+1:

**Comment by fuksi** [comment]
Error on gulp prod. Can't merge this yet!

image

**Comment by aneeshd16** [comment]
+1
@prasht63 try removing only these
* karma-babel-preprocessor
* karma-browserify
* karma-chrome-launcher
* karma-coverage
* karma-firefox-launcher
* karma-jasmine
* angular-leaflet-directive

**Comment by prasht63** [comment]
Ok , I will make the required changes and send a PR in a few hours.Since gulp prod now works I think this issue can take a back seat for now

**Comment by mariobehling** [comment]
I am moving this to M2. As M1 has passed. Assigning it back to Prashant as he is the one taking care.

**Comment by prasht63** [comment]
@aneeshd16 merge it.Removed only safe to remove ones

**Comment by sudheesh001** [comment]
Are we still using this ? https://github.com/loklak/loklak_webclient/blob/28cdc5897a9e0538d3809d7fba1211ef13ed6fbd/package.json#L79

**Comment by prasht63** [comment]
About the package "masonry layout" I am not sure. And "Why does the removal unused add them here?"  can you clear this.I could not get it.

**Comment by sudheesh001** [comment]
@prasht63 I meant this
https://github.com/loklak/loklak_webclient/commit/73966151ba68b6c6c20b9104251621946b8c0343

You're adding back the removed elements here

**Comment by prasht63** [comment]
because Aneesh tested them, and they were not safe to remove.

**Comment by fuksi** [comment]
Probably from some old cold that still requires masonry. We'll clean it along the way. Good work!

**Pull request merged**
