### PR TITLE
Geo suggestion

### PR DESCRIPTION
**Pull request by fuksi**
Solve #277:
- Live version to test:  http://gofullstack.me:3001/advancedsearch
- Location suggest is now using the service straight from loklak server e.g. http://loklak.org/api/suggest.json?q=singa

How accurate it's at the moment is totally based on what is available in the server. 
The main point it that it sends the right query:  
image

### CODE REVIEW

**Comment by Orbiter** [comment]
that looks nice!
Do we agree on the number of suggestions (5)? Any number is possible for loklak_server.

**Comment by fuksi** [comment]
Averagely I got at least 10-12 results from server, I choose to show 5 so it is easier to see and choose. However I would like to reorder the list from the most popular location to the least
@Orbiter, which of this field in the future would define how popular a location is? Or is it already computed from the server?
```json
     "retrieval_count" : 1,
    "message_period" : 86400000,
    "messages_per_day" : 1,
    "score_retrieval" : 0,
    "score_suggest" : 0
```

**Comment by Orbiter** [comment]
The suggestion list actually consists of two parts, which are sorted individually:
- first, a list of queries which match. They are sorted descending by the number of queries so far
- second (appended) a list of locations. They are sorted descending by the population of the place
This therefore is already 'most popular to least'

**Comment by fuksi** [comment]
@Orbiter
The `selectedby=geo` returns strange results, in both ways
http://loklak.org/api/suggest.json?q=vow&selectby=geo
or 
http://loklak.org/api/suggest.json?q=singa%20selectby=geo

I'm merging this since it rarely returns a hashtag, and I also need the server for another PR :)

**Comment by Orbiter** [comment]
@fuksi right the results are bad. That comes mainly be two reasons:
- I told you the wron parameter name, it should be source=geo, not selectby=geo
- for the word 'vow' there are actually no good completions. The algorithm returned 'something' anyway and made it with 'distance=2', which means the suggestions may differ in two characters which is really bad for a 3-character word.

I added a check for the query word length to suppress such results. An update is in place. For this case it will return no results...
http://loklak.org/api/suggest.json?q=vow&source=geo

**Comment by fuksi** [comment]
Added geo on master https://github.com/loklak/loklak_webclient/commit/b7dbbcd56642007e0fe373b9ce5b451932211046

**Pull request merged**
