### PR TITLE
Implement Connect Service & Data Source Interface #205 #206

### PR DESCRIPTION
**Pull request by zyzo**
This PR adds a new page to Loklak, accessible via navbar, dedicating to add new services #205 and data sources #206 to loklak server via webclient, and for the user to visualize the list of added services / data sources.

Not ready until PR https://github.com/loklak/loklak_server/pull/59 is merged and Issue https://github.com/loklak/loklak_server/issues/35 is resolved.

### CODE REVIEW

**Comment by zyzo** [comment]
* Access connect page from nav bar. Click `My Connections` to open : 
screenshot from 2015-07-04 12 49 53

* Data Sources Page. The data displayed is just some stubs as no real data source info is available on server-side yet : 
screenshot from 2015-07-04 12 51 40

* Others pages : Coming soon
screenshot from 2015-07-04 12 52 09

**Comment by prasht63** [comment]
@zyzo Should I see a form on clicking Add data source? How do we add a data soure now?

**Comment by mariobehling** [comment]
@zyzo How can I tell the system the URL of a FOSSASIA API File (e.g. https://raw.githubusercontent.com/fossasia/fossasia-communities/master/China/BeijingLinuxUserGroup-api.json)?

**Comment by zyzo** [comment]
@mariobehling That would be the feature described in #35. We need to somehow save the source metadata (url, importer, ..) to loklak.

**Comment by zyzo** [comment]
@prasht63 I'm on it :)

**Comment by zyzo** [comment]
@prasht63 add data source form is functional. 
TODO : 

- [ ] Add source_type selector to form. @Orbiter : is there a way to get source types list with loklak API ?
- [ ] Add map_type chooser to form. I'm thinking about an input panel with 2 column. First is user field name, second is valid tweet field name. Same here : is there a way to get all valid tweet field names ? If not, I guess the easier solution would be declare & store that list statistically in loklak_webclient.

**Comment by zyzo** [comment]
New add form screenshots : 
screenshot from 2015-07-06 11 06 58
screenshot from 2015-07-06 11 07 32
screenshot from 2015-07-06 11 07 52

**Comment by mariobehling** [comment]
Is it possible to actually test something in the interface already? Could we merge this and iterate from here? I would like to see some UI in action to understand the flow better.

**Comment by zyzo** [comment]
The data source list is stubbed, but this could surely be a checkpoint to iterate from. @prasht63 Could you please review & merge ?

**Comment by prasht63** [comment]
Merging #285

**Pull request merged**
