### PR TITLE
Feature/app rest api

### PR DESCRIPTION
**Pull request by aneeshd16**
#382

Try the CRUD operations on saved walls.

I am expecting a few bugs, please test before merge.

IMP: Open this URL in the browser to clear all existing data before testing:
 `http://localhost:9000/api/account.json?action=update&data={"screen_name":"aneeshd16","apps":{}}`

### CODE REVIEW

**Comment by fuksi** [comment]
Oauth is not working :) To reproduce the error:
- gulp dev -> Chrome opens a new tab. Oauth still working (since cookies are there).
- click on wall tab
- look in gulp dev console
```bash
[13:28:45] Finished 'dev' after 36 s                                                                    
OAuth Shim listening on 3002                                                                            
d:\public_html\loklak_webclient\oauth-proxy\api.js:31                                                   
        if (data.apps[req.params.app])                                                                  
                     ^                                                                                  
TypeError: Cannot read property 'wall' of undefined                                                     
    at Request._callback (d:\public_html\loklak_webclient\oauth-proxy\api.js:31:22)                     
    at Request.self.callback (d:\public_html\loklak_webclient\oauth-proxy\node_modules\request\request.j
s:197:22)                                                                                               
    at Request.emit (events.js:110:17)                                                                  
    at Request.<anonymous> (d:\public_html\loklak_webclient\oauth-proxy\node_modules\request\request.js:
1050:14)                                                                                                
    at Request.emit (events.js:129:20)                                                                  
    at IncomingMessage.<anonymous> (d:\public_html\loklak_webclient\oauth-proxy\node_modules\request\req
uest.js:996:12)                                                                                         
    at IncomingMessage.emit (events.js:129:20)                                                          
    at _stream_readable.js:908:16                                                                       
    at process._tickCallback (node.js:355:11)                                                           
[13:29:01] [nodemon] app crashed - waiting for file changes before starting...                          
```
- Try to create the wall, nothing opens
- Refresh the page, session is lost. Try to login, the error occurs
image

`http://localhost:3002/oauthproxy?client_id=0CbZ9fnYkxdBB7mRsbGtggkiW&response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fredirect&display=popup&scope=&state=%7B%22client_id%22%3A%220CbZ9fnYkxdBB7mRsbGtggkiW%22%2C%22network%22%3A%22twitter%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_c2579hvd%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22http%3A%2F%2Flocalhost%3A3000%2Fredirect%22%2C%22scope%22%3A%22basic%22%2C%22oauth%22%3A%7B%22version%22%3A%221.0a%22%2C%22auth%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Fauthenticate%22%2C%22request%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Frequest_token%22%2C%22token%22%3A%22https%3A%2F%2Fapi.twitter.com%2Foauth%2Faccess_token%22%7D%2C%22oauth_proxy%22%3A%22http%3A%2F%2Flocalhost%3A3002%2Foauthproxy%22%7D`

**Comment by aneeshd16** [comment]
Did you clear all data with http://localhost:9000/api/account.json?action=update&data={"screen_name":"aneeshd16","apps":{}}

**Comment by fuksi** [comment]
That helped with the session thing, but still after this, nothing happens.
image

The error in dev console should be clear for you :)
```bash
XMLHttpRequest cannot load http://localhost:3002/thienphucstuff/wall. The 'Access-Control-Allow-  
Origin' header has a value 'http://localhost:3001' that is not equal to the supplied origin. Origin 
'http://localhost:3000' is therefore not allowed access.
```

**Comment by aneeshd16** [comment]
Super easy to fix. Go to `loklak_server/data/settings/customized_config.properties`. Set the domain to 'http://localhost:3000`. Restart server and webclient.
Documentation update needed!

**Comment by Orbiter** [comment]
>Go to `loklak_server/data/settings/customized_config.properties`. Set the domain to `http://localhost:3000`. Restart server and webclient.
Documentation update needed!

please fix the documentation yourself or write an issue

**Comment by aneeshd16** [comment]
Closing this, opening a new PR with more features.

**Comment by mariobehling** [comment]
Please provide a link to the documentation you wrote/updated.

**Comment by aneeshd16** [comment]
@mariobehling there is no "documentation update" needed. I wrote that incorrectly. In the local setup, the `domain` variable was incorrectly set to `localhost:3001` even though our domain is `localhost:3000`. This variable has not been used till now, so it didn't cause any problems. Now that we are using it, we need to change it to the correct value. **No change required on our deployment**.

**Comment by mariobehling** [comment]
Ok, good. Thank you.

**Pull request closed without merging**
