### PR TITLE
Fixes issue #536

### PR DESCRIPTION
**Pull request by sopu**
screenshot from 2016-03-07 13 00 10

### CODE REVIEW

**Comment by aneeshd16** [comment]
@sopu What happens if you click that marker when it is right at the top of the map?

**Comment by sopu** [comment]
@aneeshd16 The map shifts downwards to accommodate the pop-up

**Comment by aneeshd16** [comment]
Alright great! Will test and merge.

**Comment by sopu** [comment]
@aneeshd16 Suggestions?

**Comment by sudheesh001** [comment]
@sopu Is there a specific reason behind the CSS change rather than using the `panTo` functionality ?

http://leafletjs.com/reference.html#map-panto

**Comment by sopu** [comment]
@sudheesh001 Yeah actually a small change [here](https://github.com/loklak/loklak_webclient/blob/master/app/js/controllers/map.js#L46) could do the trick.

**Comment by mariobehling** [comment]
@sopu What is the status of this PR? Can it be used and merged?

**Comment by sudheesh001** [comment]
I am not sure this is the right way to do this patch, as mentioned we need to go with PanTo() and make the pan to the center. I am closing this since it's old and we can work on a newer patch for this. 😄

**Pull request closed without merging**
