### PR TITLE
Wall card layout

### PR DESCRIPTION
**Pull request by aneeshd16**
#319 (details here)
Test link: http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/VJRDSK_c

* Fixed height, variable width 3 rows layout on any screen size
* Variable width details: https://github.com/loklak/loklak_webclient/issues/319#issuecomment-130365241
* Font, etc automatically adjusts according to screen size
* Aspect ratio of images is preserved
* If images has vertical orientation, space is not wasted
* When leaderboard is enabled, font size is decreased

### CODE REVIEW

**Comment by fuksi** [comment]
Styles are broken in small screen-sizes. You might also  want to add some prefixes to the header styles. It's strange in IE & Edge. Okay people who uses loklak probably does not use IE, but Edge is totally possible :)
image

**Comment by mariobehling** [comment]
I also get "share location" on walls. This is totally useless. Could you help to fix this, please?

**Comment by aneeshd16** [comment]
@fuksi I tested this in Edge, it does work. The wall has been made for display purposes, and is not really practical for mobile devices as of now.
untitled

@mariobehling, I will ask @sudheesh001 to do this asap.

**Comment by mariobehling** [comment]
@aneeshd16 I see scroll bars on the right and bottom. Please check how to avoid them.

**Comment by aneeshd16** [comment]
@mariobehling those scroll bars are from the "Web Note" view of Edge, and not the site itself. There are no scroll bars on the site.
image

**Comment by mariobehling** [comment]
Good. Excellent.

**Comment by mariobehling** [comment]
* [ ] Please decrease the space on the left hand side to the edge. Compare with tweetwall, what makes sense.

**Comment by sudheesh001** [comment]
As far as what I can see
```js
if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } 

  function showPosition(position) {
    latitude = position.coords.latitude;
    longitude = position.coords.longitude;
    tempArray.push(latitude);
    tempArray.push(longitude);
    sendPositionDetails(latitude, longitude);
  }
```
is what shows up when I inspect the production but this function has been changed so that the navigator.geolocation gets executed only when a tweet modal by the name `#myModal` as is on this code
```js
$('#myModal').on('shown.bs.modal', function (e) {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } 
})
```
Also another location in the controller is
```js
$rootScope.root.getLocation = function() {
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(setPosition);
        }
        else {
            alert("Geolocation isn't supported by this browser");
        }
    };
```
which can only be executed when the function is invoked and this function isn't invoked at all from the wall view.

**Comment by aneeshd16** [comment]
Done
After:
image
Before:
image

**Comment by fuksi** [comment]
I'm merging this. The space is still there on your server, but the fix is already there. Maybe just some cache thinggy.

**Pull request merged**
