### PR TITLE
Fixes uneven images and other patches including code cleanup

### PR DESCRIPTION
**Pull request by sudheesh001**
Ready to merge
- [x] Images on home page are now aligning themselves only based on width so as to not shrink
- [x] Images for title header also align themselves based on width to avoid shrinking
- [x] A user can enter a custom location and send that along with the tweet (Removed the map icon which was present with the location because when dynamic it misses the special character and shows up as plain text, Please merge without this now)

Tests made after the latest commit
https://twitter.com/sudheesh001/status/635899585341227008
https://twitter.com/gearsystems/status/635898806546989056
https://twitter.com/gearsystems/status/635898597058310144

### CODE REVIEW

**Comment by mariobehling** [comment]
As this overlaps with a number of issues with Phuc, @fuksi please check this PR. Thank you!

**Comment by fuksi** [comment]
The mentioned points are checked.
However I notice some this showing in in connect view. Please check if you have that as well or is it just my cache, because I can't where it is coming from the code change. Otherwise, everything is good to merge. 
image

**Comment by sudheesh001** [comment]
Thanks for pointing it out @fuksi Its cleared now, It was a small issue about null which I had overlooked while cleanup when there are no data sources.

**Comment by mariobehling** [comment]
>  Images on home page are now aligning themselves only based on width so as to not shrink

This was never the goal. Where was it mentioned to create boxes with a different width? I do not understand why this has been merged. You should have mentioned the relevant issue https://github.com/loklak/loklak_webclient/issues/495#issuecomment-133568589

Please undo the home image that is out of design.

**Comment by mariobehling** [comment]
screenshot from 2015-08-26 09 39 45

**Comment by fuksi** [comment]
I also didn't even notice this. I thought the images mentioned are the images on the timeline tweets
@sudheesh001 can you clarify a bit here?

**Comment by sudheesh001** [comment]
@mariobehling I just changed the image part back to its original code and direct commit to master. I've repeatedly tested with multiple accounts to see that the images are perfectly visible and square. I don't really understand why it doesn't work for you. The image response is a perfect square image, when we scale either the width or height in responsive design , it ideally scales both of them. Here's a set of test accounts and accounts of my friends I've tested on. All of these look perfectly fine.

screen shot 2015-08-26 at 3 04 19 pm

screen shot 2015-08-26 at 3 00 22 pm

screen shot 2015-08-26 at 2 54 52 pm

**Pull request merged**
