### PR TITLE
[DO NOT MERGE] Wiki Geo Data API controller

### PR DESCRIPTION
**Pull request by jig08**
A JS controller for [Wiki GeoData AP](https://www.mediawiki.org/wiki/Extension:GeoData#API)I has been created for [loklak.net](http://loklak.net/)

This returns a JSON object of a list of articles around the given point (determined by coordinates and radius) whose one of the parameters `pageid` can be used to access the Wiki Article via `https://en.wikipedia.org/?curid=<pageid>`

_Yet to be done: Pass the `lat`(latitude) and `lon`(longitude) of the location in the `QueryCommand`._

Let me know your views, so that this can be modified accordingly.

### CODE REVIEW

**Comment by mariobehling** [comment]
How is this relevant for the web client? I dont see an issue in the web client regarding this. What feature in the web client is this related to?

**Comment by jig08** [comment]
@mariobehling I had in mind if we could have a pop-up box in [loklak.net](loklak.net) on clicking a location where the location wise Wiki-Articles could be displayed.
Else, how the Media Wiki GeoData API be implemented ? A bit clarification would be helpful :grinning: 
cc: @Orbiter

**Comment by mariobehling** [comment]
@jig08 The web client is independent of the loklak server. 

Please help to implement parsers for the server. We can follow up on features on web clients if this is needed here. At the moment, we really do need **more parsers in the loklak server** and preferably an easy way to plugin in parsers - in the server.

It would be fantastic, if we could get parsers now for the loklak servers and code that does it. We are really looking for parser code in the loklak server.

Thank you for making parsers/harvester components/indexers for the loklak server. 

So, let's focus on getting weibo parsers etc. into the loklak server.

Hope to see more code doing this in the loklak server. Cheers.

**Comment by jig08** [comment]
@mariobehling Sure. I am working on weibo.com parser *currently* and not continuing work on this wrt [Wikipedia: Add location data privided by GeoData API](https://github.com/loklak/loklak_server/issues/342) then.

**Pull request closed without merging**
