### PR TITLE
Dev login hellojs oauthproxy

### PR DESCRIPTION
**Pull request by fuksi**
New authentication method.
Read more about the approach here: https://github.com/loklak/loklak_webclient/issues/157

Live demo of this branch: http://gofullstack.me:3001/
Conflicts are already resolved before merge. 

```gulp dev´`` modified with the new approach, ```server``` task is replaced with original express server, ```oauth``` is create based on this model: https://github.com/MrSwitch/node-oauth-shim

```gulp live``` is basically ```gulp prod``` with a ```server``` task for those whose server doesn't have a serving static server

```gulp prod``` stays the same. 

Docs are coming as merging. #163

### CODE REVIEW

**Comment by aneeshd16** [comment]
Looking at the files, it seems good! Will test and merge.

**Comment by Orbiter** [comment]
:+1: go ahead! good work!

**Comment by sudheesh001** [comment]
Looks good, just reviewed :+1:

**Comment by aneeshd16** [comment]
:shipit:

**Pull request merged**
