### PR TITLE
Wall cycle

### PR DESCRIPTION
**Pull request by aneeshd16**
Sorry for the large number of tests.
* [x] Solves #462
* [x] Solves #455 (The size of the tweet box now stretches a bit to fit oversized content. More fixes also. See issue)
* [x]  Solves #444 
* [x]  Solves #436 Leaderboard upgrade. 
    * A three column layout was too messy. I settled on three tabs which cycle automatically on a time interval of 5 seconds. (Design suggestions welcome here)
image
    * The bar chart sticks to the bottom of the page. Rest of the space above it is occupied by leaderboard items
* [x] Solves #377 Options included are cycle post limit, and cycle delay time. What's not there? Animations. Haven't been able to properly animate this yet, will continue to look for solutions.
* [x] I believe #274 should also be closed unless I have misunderstood thumbnails

### CODE REVIEW

**Comment by mariobehling** [comment]
Do you have a test link, please?

**Comment by aneeshd16** [comment]
http://aneesh-ojl02abl.cloudapp.net/wall
Server was down for a while

**Comment by mariobehling** [comment]
@aneeshd16 Test system does not generate usable wall URLs: http://aneesh-ojl02abl.cloudapp.net/mariobehling/wall/
screenshot from 2015-08-25 21 22 59

**Comment by aneeshd16** [comment]
Please try logging out and logging in again. I just made this wall http://aneesh-ojl02abl.cloudapp.net/aneeshd16/wall/Ey6dgnrh

**Comment by mariobehling** [comment]
Leaderboard and Activity Calendar are not separated from the right hand screen end. 
* [ ] Please ensure there is a space area on the right.
screenshot from 2015-08-25 22 00 53

**Comment by mariobehling** [comment]
Original calendar leaves a blueish area on the right.

screenshot from 2015-08-25 22 07 42

**Comment by mariobehling** [comment]
It would be great to have the images of the @mentions as well - just like in the top twitterers.

screenshot from 2015-08-25 23 21 05

**Comment by mariobehling** [comment]
* [ ] Please try to use maximum height of images in available area
screenshot from 2015-08-25 23 24 00

* [ ] align images on the right
screenshot from 2015-08-25 23 26 46

**Comment by mariobehling** [comment]
I played around a bit with the cycle and wall options.
* [ ] Cycle Delay Time is max 20 seconds. Why? I think it could longer.
* [ ] Please increase height of form area. In some browser tests the cycle number hit the edges
* [ ] It looks like location places form area should also increase height (same as cycle) and width
screenshot from 2015-08-26 00 48 51

When testing: Strange thing, the first top tweets get exchanged. Expected behaviour: Tweets appear on top and older tweets move down. See: http://aneesh-ojl02abl.cloudapp.net/mariobehling/wall/V1ZCwhrh
screenshot from 2015-08-26 00 44 21
screenshot from 2015-08-26 00 44 03

**Comment by aneeshd16** [comment]
@mariobehling 
>* [ ] Please try to use maximum height of images in available area
screenshot from 2015-08-25 23 24 00

The width of the text container is fixed. The extra space is due to text wrapping.
Text container in red, you can see the borders of the container
image

I cannot make the image wider, and thus cannot make it taller also (to preserve the aspect ratio). I did remove about 15px of unnecessary padding from the left of the image.

**Comment by mariobehling** [comment]
@aneeshd16 Ok, thanks for the info. Let's postpone and look at this in detail later. I guess there is some CSS solution.

**Comment by fuksi** [comment]
All the points mentioned in the first post are checked again.
Notice this left whitespace if the wall is a map
image
you can of coures patch this up later

**Comment by aneeshd16** [comment]
I was adding more patches to this, but okay :)

**Pull request merged**
