### PR TITLE
Init home view

### PR DESCRIPTION
**Pull request by fuksi**
Solve #119, create a initial view, disable auto pop up login modal when load page. 
Live on http://gofullstack.me:3001/

image

### CODE REVIEW

**Comment by sudheesh001** [comment]
screen shot 2015-07-15 at 10 34 36 pm
screen shot 2015-07-15 at 10 34 32 pm

Home page looks good but the post login view has shrinked in body size.

**Comment by fuksi** [comment]
It didn't shrink. The post login has always been placed in a bootstrap container. If the post login stretch 100% width then it would be too wide :)  It's good to merge then.

**Comment by mariobehling** [comment]
Ok, this is maybe a temporary solution, but not a working initial home view with map, wall etc. on the top. Please provide a mockup first.

**Comment by mariobehling** [comment]
An initial homescreen is something like what you see at twitter when you are not logged in.
screenshot from 2015-07-15 19 36 29
This actual depends on accounts etc. 
Please postpone details for this until accounts are ready and keep the pop up.

**Comment by mariobehling** [comment]
@fuksi  Please delete the branch after merging.

**Pull request closed without merging**
