### PR TITLE
Wall design patches

### PR DESCRIPTION
**Pull request by aneeshd16**
1. [x] Should solve #331 
2. [x] Should solve #329 
3. [x] Should solve #332 
3. [ ] Should solve #333 
4. [x] Profanity filter is enabled. (How to test is up to you :wink:)

Link for testing: http://aneesh-ojl02abl.cloudapp.net/wall (Icons do not work on my server, will work when deployed)

### CODE REVIEW

**Comment by mariobehling** [comment]
Looking at your buttons I see that they are using another blue color than the twitter button colors on the main page. 
* [ ] Please adjust all blue color buttons to the same color

screenshot from 2015-08-03 10 22 31

**Comment by fuksi** [comment]
Regarding #333
- If the event field is empty, there is currently no err message and the wall is created anyway
- I'm not seeing this at the moment

**Comment by aneeshd16** [comment]
Validation is fixed, kindly check. As for Leaderboard type, comments here: https://github.com/loklak/loklak_webclient/issues/333#issuecomment-127264302

**Comment by aneeshd16** [comment]
@zyzo has already changed the button styles, so those will be automatically visible when PR #427  is merged.

**Comment by fuksi** [comment]
Checked.

**Pull request merged**
