### PR TITLE
Dev search v106

### PR DESCRIPTION
**Pull request by fuksi**
Another approach on arranging components in merged `Map` & `Home` view.
- Related comment : https://github.com/loklak/loklak_webclient/issues/452#issuecomment-132944979
- Test server: http://gofullstack.me:3001/

I'm not expecting the PR to go smoothly :) styles are heavily over written in many places. Please feel free to comment on how you experience this new layout.

No hurry to merge, if the layout is okay, I'll need to add some comments before merging.
Cheers.

### CODE REVIEW

**Comment by mariobehling** [comment]
At the moment I do not see the background, but it feels good already.

**Comment by mariobehling** [comment]
Ok, it is showing up now. Great! Small details:

* [ ] in map view the text is overlapped. I think there is no need to show number of followers etc. here. So you can move the activities slightly higher
screenshot from 2015-08-21 10 35 59

*  [ ] the right bar: The effects for in/out are different. Please use "push" for both as shown here http://tympanus.net/Development/SidebarTransitions/

**Comment by mariobehling** [comment]
* [ ] Rename "Return to timeline" to "Timeline"
* [ ] Currently the button for map/timeline shows up on top of people's profile banner. This is not the best solution. What other options are there? Maybe above that area? We might also mix twitter and other services e.g. when we integrate Weibo from China. So there might be more than one profile badge on this page. Let's think about this later. For now, let's keep the profile banner untouched.
* [ ] Please remove the large spaces in the profile area a) below the Username (above the @mariobehling) b) between tweets/followers/folllwing/ and the numbers below c) @username should not be italic

**Comment by fuksi** [comment]
The new version can be testest again at: http://gofullstack.me:3001/  
- Old transition time 1.5 (0.5 for things to fade out, 1s for timeline/user to move right)
- New transition time 0.9 (0.3 ..., 0.6 ...)

**Comment by mariobehling** [comment]
As you are working on this page, it might be close to cover this issue as well now regarding decreasing the area between boxes: https://github.com/loklak/loklak_webclient/issues/491

**Comment by mariobehling** [comment]
> Old transition time 1.5 (0.5 for things to fade out, 1s for timeline/user to move right)
New transition time 0.9 (0.3 ..., 0.6 ...)

Not sure, which is which. 
I think the transition for the side bars and map to appear can be even shorter.

**Comment by fuksi** [comment]
`Not sure, which is which.`
Those were between timeline view & map view
`I think the transition for the side bars and map to appear can be even shorter.`
Reduced it to 0.3s (from 0.3s)
`As you are working on this page, it might be close to cover this issue as well now regarding decreasing the area between boxes: #491`
Reduced

You can also review the above in the same link: http://gofullstack.me:3001/

I'm merging this since I want to move forward with other map related issues. (I can of course check out a new branch, but styles merging conflict can be unnecessary time-consuming in the future).

Feel free to comment here if there are some small things those needed to be change. I can include it in the next merge. 
Cheers!

**Comment by mariobehling** [comment]
Thanks! Good job.

**Pull request merged**
