### PR TITLE
Fixes #460

### LINKED ISSUE #460: Reports not displaying account user, country wise info and having style issues
1. Clicking on "report" results in "Sorry we did not find anyone with this account".
screenshot from 2015-08-12 10 19 55

2. Correct: report:username Incorrect: report:@username. 

3. It does not look like fitting into the style and there are round edges between the columns.
screenshot from 2015-08-12 10 21 22

4. Country wise followers not available
screenshot from 2015-08-12 10 21 55

5. Testing incognito should not be possible. I see columns without content. That should not happen. In logged in mode here should be the data of the account holder. Is that the case?
screenshot from 2015-08-12 09 19 59

### PR DESCRIPTION
**Pull request by prasht63**
1.Test Link : http://loklaktest.cloudapp.net:3000 
2.Tests
- [x] Tables should not have rounded borderd
- [x] Report heading should be report:screenname
- [x] On clicking analyze the analysed data of previous user should vanish and a loading message should come
- [ ] Going incognito should popup signup message modal

### CODE REVIEW

**Comment by prasht63** [comment]
image

@mariobehling Country wise followers for you doesnot show up on Loklak.net because the data is not provided by loklak.org, may be the data stored in RAM misses that, my local test server shows country info for you.In case you don't see data for you try with a new screen_name. Also these followers data range in 20-30MBs so it takes sometime to analyse it.Right now I am analysing only 20000 followers.Should we reduce it or give the user option to set the no. of followers to analyze.

**Comment by mariobehling** [comment]
Please test this with your own user account:
1. login
2. go to http://loklaktest.cloudapp.net:3000/report
3. See: There is no report. Same on loklak.net/report
4. Reload solves this, sometimes solves this issue. BUT: Expected behaviour is, that the report shows up right away.

screenshot from 2015-08-19 10 18 39

**Comment by mariobehling** [comment]
As pointed out a number of times the user banner does not show up correctly.

Current:
screenshot from 2015-08-19 10 22 06

Expected:
screenshot from 2015-08-19 10 23 13

**Comment by prasht63** [comment]
the user banner url which comes from loklak is used to display this.The
banner img data is incorrectly stored in Loklak.The banner is displayed
correctly in most cases. Try hpdang

**Comment by mariobehling** [comment]
I tried a number of accounts and they do not work. On the main page it does work.

**Comment by mariobehling** [comment]
1. Create a separation between sidebar area on the right
2. Increase circle diagram and move it more to the left
3. Add a table column with number of followers
4. Change color of table heading and create space between main bar and tables

5097830a-4671-11e5-8262-7c6cc1f8d592

**Comment by mariobehling** [comment]
hpdang

Twitter
screenshot from 2015-08-19 11 09 26

Loklak Report
screenshot from 2015-08-19 11 08 57

**Comment by mariobehling** [comment]
report:username is not centered
screenshot from 2015-08-19 11 13 01

**Comment by mariobehling** [comment]
* [ ] Going incognito should popup signup message modal + It should not let the anonymous user generate reports. Please compare with /wall and implement same behaviour for non logged in users. The report page should not be available for anonymous users. At the moment I can simply click away the login screen.

screenshot from 2015-08-19 11 51 59

**Comment by mariobehling** [comment]
Followers Distribution, please change:

* [ ] "Greater than 100000" to ">100000"
* [ ] "<200" to "100-200"
* [ ] add "<100"

**Comment by prasht63** [comment]
I will make the changes and send a PR in a few hours

**Comment by prasht63** [comment]
Changes made 
- [ ]  the user banner does not show up correctly.
- [ ] Create a separation between sidebar area on the right
- [ ] Increase circle diagram and move it more to the left. --> Increasing circle can't be done without increasing the div since it is set by Chart.js internally based on div size.
- [ ] Add a table column with number of followers
- [ ] Change color of table heading and create space between main bar and tables
- [ ] report:username is  centered
- [ ] Going incognito should popup signup message modal + It should not let the anonymous user generate reports. Please compare with /wall and implement same behaviour for non logged in users. The report page should not be available for anonymous users. At the moment I can simply click away the login screen.
Test Link : http://loklaktest.cloudapp.net:3000
image

**Comment by mariobehling** [comment]
Please check the erros on the travis build. Testing on your test server is not successful. See below.

screenshot from 2015-08-20 00 26 10

**Comment by mariobehling** [comment]
Table
* [ ] First column on table one is standard. On table two it is bold. Why? Just keep everything standard no need for bold.
* [ ] Ensure first column is wide enough to show "United States" in one line
* [ ] Do not use italic for second and third columnt
* [ ] First column - align left
* [ ] Second/third column - center

**Comment by aneeshd16** [comment]
@prasht63 use `gulp live` on your server instead of `gulp dev`

**Comment by prasht63** [comment]
@mariobehling @aneeshd16 Test link same as above.
Snapshot : 
image
About that glitch message, it happens when the server sends a bad response.

**Comment by mariobehling** [comment]
Good job. Thanks!

**Comment by mariobehling** [comment]
Report numbers seems to be wrong and different between what is shown in the table and the diagram. 
screenshot from 2015-08-20 22 02 40

**Comment by mariobehling** [comment]
Follow up issue here https://github.com/loklak/loklak_webclient/issues/508

**Pull request merged**
