### PR TITLE
#247 Implementation of the services, small bug on hello being a function

### PR DESCRIPTION
**Pull request by sudheesh001**
Things to test:
- [x] get the ID of the tweet and the username of the person whose tweet you want to favorite
- [x]  Click on the favorite button once
- [x] Go to the url https://twitter.com/username/status/id and check if the favorite worked.
- [x] Updated tweet box with the button turned into a file picker.

### CODE REVIEW

**Comment by prasht63** [comment]
I am not able to figure out what is wrong. I get a lot of console errors
image

**Comment by sudheesh001** [comment]
All the errors except the last one are because of images which are missing the 404 with Twitter images retrieval , would there be something that could clear the last issue thats there.

**Comment by prasht63** [comment]
Hi @sudheesh001 I have found the bug and posting a fix here, you were not including the HelloService properly.Also from next time please work on a branch in the loklak_webclient where we others have write permissions. :+1: 
```
directivesModule.directive('status', ['$location', '$timeout', '$rootScope', 'HelloService', 'AppSettings',   function($location, $rootScope, HelloService) {
```

**Comment by sudheesh001** [comment]
@prasht63 Nope I still have the same error.

**Comment by aneeshd16** [comment]
Can you change the favorite icon to a different one (gold/yellow) similar to twitter? There needs to be feedback whether the favourite operation worked or not.

**Pull request merged**
