### PR TITLE
Wall bug fixing

### PR DESCRIPTION
**Pull request by aneeshd16**
* [ ] Check if bugs that are checked in #252 are solved
* [x] Check if #253 is solved

### CODE REVIEW

**Comment by fuksi** [comment]
#253 is solved.
About #252 ticks:
- I'm not sure this is how instagram picture should render. Also none of the other pictures are rendered.
image
- You might want to center things in small size:
image
- And also smaller
image

**Comment by aneeshd16** [comment]
@fuksi, yes the card layout is proving to be a little troublesome. Any suggestions on how to display images in card layouts?

**Comment by fuksi** [comment]
This is somewhat like I did in search view, in card layout ,what you can do is:
- If you want to allign the height of the card. First you set a fix height for everycard
- Divide the proportion of height you want for tweet text and tweet picture, and then set the max-height for them, overflow hidden the rest.
- Click on the the content the first time will show the rest of the content
- Another click will activate the content (e.g. show photoswipe)

**Comment by aneeshd16** [comment]
That's good, but the wall is supposed to work without any user interaction.

**Comment by fuksi** [comment]
Merging now. You can pretify the cards layout when you find the change. Now it's better than nothing :)

**Pull request merged**
