### PR TITLE
Implemented local auth with passportjs and jwt

### PR DESCRIPTION
**Pull request by leonmak**
User should have mongodb installed, test db is used
Then they should change the jwt secret string in
custom_configFile.json.

xf9kmzzgkc

Stored as such:
screenshot 2016-06-05 10 59 28

### CODE REVIEW

**Comment by shivenmian** [comment]
@leonmak I don't think a user should be able to signup that easily. If you're signing up with some details, ideally, user should get a mail to verify his account. This form imo can easily be spammed.

**Comment by shivenmian** [comment]
Besides, if you have a signup option, you should also have a Sign In option with the username / password. I don't see a Sign In option.

Also, preferably add a Confirm Password field so that the user knows he entered the password he wanted to. @leonmak

**Comment by mariobehling** [comment]
@shivenmian Yes, the sign up process should be very simple. Some features can be activated only after the email is confirmed. Please compare the sign up process at twitter itself for example.

@leonmak There is no need to provide the name to sign up. Email is enough.

**Comment by mariobehling** [comment]
screenshot from 2016-06-05 11 08 38

@leonmak Please also keep the usual top bar after login (except for the changes discussed in other issues). Use an standard image for the user profile image for the moment and implement gravatar or twitter later. We can discuss this in a separate issue then.

**Comment by shivenmian** [comment]
Also does this solve #594? If so, I guess that issue should be closed too.

**Comment by mariobehling** [comment]
Yes, but issues should be closed after we all tested the live version. Where is the system deployed, so we can test?

**Comment by shivenmian** [comment]
@mariobehling: @leonmak would know about the deployment part. I'm not really assigned to the webclient project, I just commented on this PR because I'm also working on an accounts system on loklak_server and I believe the mechanism should be more or less the same. :D

@leonmak: You should add a confirm password option (and possibly a Remember Me option too), and once user has signed up successfully, you should display a sign on the user's screen saying "An email has been sent, please verify your account". Along with the current fields that you have (hash, salt, email etc), add a boolean variable ```verified``` whose default is set to false. 

Please use an email service (you could probably use email.js although you'd know better) for the verification and send the user an auto-generated link which on clicking can POST to the webclient and set the value of ```verified``` to true. Based on the value of ```verified```, you can then have features on the webclient. 

This is an ideal setup which I myself am trying to implement on the loklak_server. You could try it too. :D

**Comment by leonmak** [comment]
@mariobehling yea will remove name and make the menu. I just wanted to demonstrate the use of mongoose for mongodb to store the accounts.

@shivenmian thanks for the feedback, I think that flow is ideal. I'm still getting familiar with the whole structure of the angular app, so the menu and forms are not finalised yet.

I'll create individual issues for the upcoming developments

**Comment by mariobehling** [comment]
@leonmak No confirm password option. We want it very very simple.

**Comment by shivenmian** [comment]
@mariobehling A confirm password wouldn't make it more complicated, it'll only make the user more confident about his password choice. But sure, it's not a big deal.

We do need a sign-in form. That's only signing up for a loklak account. We need a sign-in facility too.

**Pull request merged**
