### PR TITLE
Updated work with Geolocation and retrieving lat/long 

### PR DESCRIPTION
**Pull request by sudheesh001**
Still encountering
- [x] <s>CORS errors</s> CORS errors resolved
- [x] The search option now allows pic.twitter.com to be clickable
- [x] Image on select shows the image as a thumbnail image in the tweet box.
- [x] Tweet content don't overflow out of the box regions when there are lots of hashtags #338 
# Don't merge yet.

### CODE REVIEW

**Comment by sudheesh001** [comment]
@fuksi The required workflow is as follows
- [ ] User clicks on the get location button
- [ ]  Activates the HTML5 API to retrieve the lat and long of the user
- [ ] Stores the lat and long values in a variable
- [ ] Sends a request to that loklak server to generate a geoTile for that particular coordinate with a HTTP GET request whose result is an image MIME type (This results in the CORS Error)
- [ ] The response image should be a Blob object which should be in place of the image and then sent along like a working image upload

What is the problem ?
Code segment
```js
var requestUrl = 'http://localhost:9000/vis/map.png?text=Test&mlat='+$rootScope.root.userLocation.latitude+'&mlon='+$rootScope.root.userLocation.longitude+'&zoom=13&width=512&height=256';
        
        $http({
            url: requestUrl,
            method: "GET",
            headers: {
                'Content-Type': 'application/json; charset=utf-8'
            }
        }).success(function(response) {
            var selectedFileInBlob;
            console.log("Successfully retrieved for "+requestUrl);
        });
```
Variation
```js
var requestUrl = 'http://localhost:9000/vis/map.png?text=Test&mlat='+$rootScope.root.userLocation.latitude+'&mlon='+$rootScope.root.userLocation.longitude+'&zoom=13&width=512&height=256';
        $http.get(requestUrl)
            .success(function(response) {
                $rootScope.root.geoTile = response;
                console.log("Successful Query to "+requestUrl);
            });
```
Approach
1. Specify a header with the XHR request
2. Toggle the CORS configuration flags on the server to see if turning them false / true would make a difference.

**Comment by fuksi** [comment]
Assign back to @prasht63 since I believe the CORS problem is solved.

**Comment by prasht63** [comment]
@sudheesh001  is it ready to merge? or work pending?

**Comment by sudheesh001** [comment]
Current status of this commit is able to close all issues in M2.5 assigned to me https://github.com/loklak/loklak_webclient/issues?q=is%3Aopen+is%3Aissue+assignee%3Asudheesh001+milestone%3A%22Milestone+2.5+Sprint%22

**Pull request merged**
