### PR TITLE
Fixes #92 Post Tweet feature Implemented through modal

### LINKED ISSUE #92: POST tweets to twitter after user authentication from the loklak app

### PR DESCRIPTION
**Pull request by prasht63**

### CODE REVIEW

**Comment by sudheesh001** [comment]
Please pull changes from master and test again, seems to be crashing for me, I am unable to see the signup modal on page load, it just gives me a dull background.

**Comment by mariobehling** [comment]
@prasht63 Please reference the relevant issues for PRs in future.

**Comment by sudheesh001** [comment]
I think this missed the auto referencing because of the `.` after the `92`, making the edits.

**Comment by sudheesh001** [comment]
Integrated with the 53e1f1f55d5463c926a86440022f6f5164a3384c This is good to close. Thanks @prasht63

**Pull request closed without merging**
