### PR TITLE
Display real data source information

### PR DESCRIPTION
**Pull request by zyzo**
NOTE : This is dependent on https://github.com/loklak/loklak_server/pull/83 so please don't merge it until the server part is merged. 

Features : 
* Display REAL information about imported source (url, importer, created/modified time, ..)
* Add new connection in different format via `addConnection/:format` (`addConnection` is defaulted to geojson)

TODO : 
* [x] currently the data source list is only loaded once when opening the page. It needs to be refreshed more at important moment (moment of opening the modal, when adding new source, button refresh ?)
* make the list more useful
    - [x] clicking on source type field should shortens the list by filtering by that source type.
    - [ ] clicking on the number of messages should display the list of messages
    - [x] clicking on a row should display a more detailed info panel about the import profile (harvesting frequence, lifetime) and let the user modify it
* [x] filter request with bad format value to `addConnection/:format` (should display 404 error)
* [x] EDIT & DELETE data source (server side edit is ready, delete requires some more work)

### CODE REVIEW

**Comment by zyzo** [comment]
Some screenshots: 
screenshot from 2015-07-24 11 31 49

screenshot from 2015-07-25 12 20 54

**Comment by mariobehling** [comment]
It looks like "edit" and "delete" is missing, if I want to change anything about this.

**Comment by zyzo** [comment]
Edit & delete buttons added along with data source detail panel http://loklak-client.danghaian.com/dataConnect. 

Only harvesting frequence & lifetime are editable, since other fields are either not relevant for edit (created_time, last_modified) or it makes more sense to create new datasource than edit old one's (screen_name, source_url, source_type, ..).

**Comment by mariobehling** [comment]
Questions:
* Ninux.json is in twitter category?
* Spell check of everything, please: Lastest?
* Please test with different resolutions overlap of importer/created time
* still not possible to delete source

screenshot from 2015-07-29 19 28 25

**Comment by zyzo** [comment]
@mariobehling 
> Ninux.json is in twitter category?

While waiting for https://github.com/loklak/loklak_server/pull/84 to be merged there is only few available source types to test with : fossasia & twitter . 

> still not possible to delete source

to be able to edit & delete the source, please click on each source. 

screenshot from 2015-07-30 08 54 09


Thanks for the inputs. I'm working on other reported issues.

**Comment by mariobehling** [comment]
Let's make the design closer to the other styles. Also consider the logic of the interface. The sorting of "data, email, IoT" should not work in the same as the wall. In the wall the design goes through 3 steps from top to down. This is not the case here. Hence the design should be different. Nevertheless "add buttons" position and colors should follow the main design.

Please:
1. General
* [ ] Change position "Add Connection" to top right
* [ ] Change button colors to match the blue "tweet" button from the start page, e.g. "edit" button "add connections" button
* [ ] instead of the rosy color, please re-use one of the grey/grey-blue colors from the scheme (e.g. check what is used at the wall editor)

screenshot from 2015-08-03 15 09 01

2. Structure
* [ ] Please make it easy for the user to make less clicks. Show Active source right on the connection page. (The wall pages also shows the active walls on the page right away.)

3. Import
* [ ] This can be implemented as a step by step process similar to creating a wall. Please reuse the design here (some ideas below)

screenshot from 2015-08-03 15 38 02

**Comment by zyzo** [comment]
To implement the new import process, following things are needed from server : 

- [ ] ability to let users specify `harvesting_freq` & `lifetime` at import time (when pushing things to /api/push/*.json)

- [ ] the list of source types & related information as an api endpoint. Currently the list is hardcoded as an [angular service]. 

- [ ] the list of loklak message field, to be able to implement an user-friendly field mapping step.

**Comment by zyzo** [comment]
@prasht63 Do you mind taking a look & merge this ?

**Comment by prasht63** [comment]
Can you tell me what should I test ? Thanks! :)

**Comment by zyzo** [comment]
Hi @prasht63. A few things to test :
* New add connection process
  * [ ] Click on add connection should open an overlay
  * [ ] Choose a source type should trigger open the next page (Add source url & info)
  * [ ] Enter invalid source url should display an error message and icon. Enver valid source url should display a checked icon. During validation there is a waiting icon.
  * [ ] Enter harvesting frequency & lifetime work well
  * [ ] Load dynamically field when enter map rule work
  * [ ] After submitting a new connection, the connection should be added to the list of connections (`/dataConnect`).

* Connection list page
  * [ ] Edit & delete connection work (open by clicking on a row)

Otherwise it would be great to have your inputs on the design, whether it is good & consistent. Testing server is up http://loklak-client.danghaian.com/dataConnect.

**Comment by mariobehling** [comment]
* [ ] Adjust overlay size to screen (same as wall). See comparison below.
screenshot from 2015-08-10 12 41 52
screenshot from 2015-08-10 12 41 52

* [ ] Data should be available for a certain account only and not for anonymous at all.
I am not sure, if there is a misunderstanding of data. Data is always attached to an account, but in loklak server we also store it even though a user has deleted it. Data can also be attached by different users. Then we will do the something similar to Facbook-Likes. Think of "5 people like this page" - we have "5 users have shared this data set".
* [ ] Step 2: "Check for updates every" - use 6 hours as a standard choice here.
* [ ] Step 2: "Enter 'forever' for ever-lasting data" change to "Leave empty for continuous updates."
* [ ] Step 3: Latitude/Longitude: Implement a map to choose an icon from (Or open an issue to do this later)

**Comment by mariobehling** [comment]
@zyzo Please explain what does screen_name and text field mean? Where do you show this data?

**Comment by zyzo** [comment]
@mariobehling screen_name and text fields are message fields once saved in loklak. It's also what is returned by the search engine. An example is mailchimp : they show their field as label in the first column and other service field in second column as input https://connect.mailchimp.com/how-to/91. Even though their field is in friendlier text format. Maybe a type of field name - field label mapping should be performed here as well.

**Comment by zyzo** [comment]
> Data should be available for a certain account only and not for anonymous at all.
I am not sure, if there is a misunderstanding of data. Data is always attached to an account, but in loklak server we also store it even though a user has deleted it. Data can also be attached by different users. Then we will do the something similar to Facbook-Likes. Think of "5 people like this page" - we have "5 users have shared this data set".

Now what we save when pushing a source url, is the messages in that source, and an import profile, which is attached to a client. That's where the attachment user-message happens. The constraint must login before adding connection is not implemented yet therefore the list displaying is also the full list without authentication. But implementing the contraint also raises a concern : how the server knows that a client is authenticated ? More in https://github.com/loklak/loklak_server/pull/83#issuecomment-124116874

> Step 2: "Enter 'forever' for ever-lasting data" change to "Leave empty for continuous updates."

I think there is a misunderstanding on what lifetime means. It's the date when the message is no longer valid, not the update frequency.

> Step 3: Latitude/Longitude: Implement a map to choose an icon from (Or open an issue to do this later) 

For mapping rules, what user has to enter is the name of the field in their custom data that correspond to loklak field, not a real value. The real value is extracted from the data.

**Comment by mariobehling** [comment]
> The constraint must login before adding connection is not implemented yet therefore the list displaying is also the full list without authentication. But implementing the contraint also raises a concern : how the server knows that a client is authenticated ?

Added https://github.com/loklak/loklak_webclient/issues/447 to follow up.

> I think there is a misunderstanding on what lifetime means. It's the date when the message is no longer valid, not the update frequency.

Please define "message". Is it the data collected? Why do we need an expiration date?

>> Step 3: Latitude/Longitude: Implement a map to choose an icon from (Or open an issue to do this later)

> For mapping rules, what user has to enter is the name of the field in their custom data that correspond to loklak field, not a real value. The real value is extracted from the data.

Please give examples. I do not understand that. Then why is there one field for lat and one for longitude?

**Comment by mariobehling** [comment]
Step 3:

* [ ] screen_name is a relevant field for the system, but the user does not need to understand this, right? Please rename this to "Name"

* [ ] Enter help texts below field
a) give examples what to enter at "screen_name, latitude, longitude, text", e.g. Please enter ....
b) Tell us why this is important and where it will show up, e.g. This info will be displayed at...
screenshot from 2015-08-11 09 39 36

* [ ] There are grey fields. What are they for?
screenshot from 2015-08-11 09 40 19

**Comment by zyzo** [comment]
@mariobehling The grey fields are previews of the data that correspond to entered custom field. 
Only when a source type is chosen and a source url is validated (green check mark), a small caret appears next to 'Final step : map your data .. ' which can be toggled to show source data : 

screenshot from 2015-08-11 16 29 59

When user enters a field that exists, the grey area is filled with corresponding content : 

screenshot from 2015-08-11 16 30 12

What needs to be done is adapt the UI to show multiple values if the source has many messages. Mailchimp does this with a rectangle blocks UI : 1 block per field and multiple values are displayed as a list at the bottom of each block (ref: http://kb.mailchimp.com/lists/growth/import-subscribers-to-a-list)

**Comment by mariobehling** [comment]
> Username: state.logo?

Is this an example? As a user I would not know that I have to enter this value here.

* Helper Text needs to be something that makes sense e.g. "Please enter xyz in this field. The field will then show up at place uvw."

**Comment by zyzo** [comment]
> Is this an example? As a user I would not know that I have to enter this value here.

It's just to demonstrate the fact that the input supports accessing deep json field. A more relevant value here is `name`.

I also combined that latitude and longitude field into coordinates. Before that I thought it is a nice idea, since coordinates can be represent in lots of ways : 
```javascript
{
 'lat' : '123',
 'lon': 456
}
```
or `[lat, lon]`, but once saved in loklak the format has to be `[lon, lat]`. However, the server hasn't support separate coordinate fields as map rules yet so I'll come back later to this when I have a chance.

**Comment by mariobehling** [comment]
> It's just to demonstrate the fact that the input supports accessing deep json field. A more relevant value here is name.

Ok, thanks. In order to understand the usefulness of things, please provide a useful example. I am still not clear, what username should be entered here. Where does the username come from? loklak, twitter, the website, username of ...?

> I also combined that latitude and longitude field into coordinates. ...t so I'll come back later to this when I have a chance.

Ok, good. Please create an issue for that if relevant.

**Comment by mariobehling** [comment]
* [ ] "Delete" Please open a confirmation box "Are you sure, you want to delete this? Buttons: Delete | Cancel.
* [ ] On "Edit" please reopen wizard. (Same as edit wall. The wall wizard reopens.)

**Comment by mariobehling** [comment]
* [ ] show next step without scrolling if possible e.g. on step 1
* [ ] do not show button bar
* [ ] only show scroll bar on the right, if there is something to scroll to, e.g. on step 1 everything should fit in here already
* [ ] use transparent pngs for logos and and do not overlap text
* [ ] center logo text (Fossasia is correctly written FOSSASIA)
* [ ] find suitable logo substitute for GeoJSON logo

screenshot from 2015-08-11 12 24 59

**Comment by mariobehling** [comment]
Here is a public logo of FOSSASIA as a png: https://drive.google.com/file/d/0B4n_k1amQnpydTdPRm5nMWowLVE/view 
Please reduce resolution and size to adapt to area.

**Comment by mariobehling** [comment]
here are the Freifunk Styles. Just take care to make the background transparent where necessary: https://wiki.freifunk.net/Freifunk-Styles

**Comment by mariobehling** [comment]
@zyzo Please talk to @fuksi about authorization to access the "connect" area and features. There are a number of related issue. This one might be relevant: https://github.com/loklak/loklak_webclient/issues/408

**Comment by mariobehling** [comment]
@zyzo We need to advance and this PR is taking 16 days now. Most changes are currently small design changes. Please take care of these and @prasht63 then merge the PR.

@zyzo Regarding the authorization/authentication and remaining issues here please open a separate PR.

**Comment by zyzo** [comment]
>  As a user I am still not clear, what username should be entered here. Where does the username come from? the JSON which field, loklak, twitter, the website, username of ...?

Previously when I didn't know which user to attach the message to, I let user select the username (screen_name) directly from the source data. Now that we decided to attach the message to currently logged in user, this field is unnecessary. I will update it in another PR. 

>  On "Edit" please reopen wizard. (Same as edit wall. The wall wizard reopens.)

This is not easy as several parameters can't be (easily) edited : source url, source type, and map rules. The two formers can't be easily edited since we decided to keep all versions of an import profile, a.k.a when the source is edited we don't override the last import profile and message but create new ones with new mtime value. So changing these require changing all import profile versions. About the map rule, it is right now not saved therefore can't be edited.

About other issues, I believe I fixed them all. @prasht63 could you please merge this ?

**Comment by mariobehling** [comment]
Ok, good job!

**Pull request merged**
