### PR TITLE
Fix #419 Display spinner icon & hide loklak logo while loading resources

### LINKED ISSUE #419: Display spinner icon in waiting state.
I think we lack a spinner icon similar to twitter when loading heavy services. In loading state, the middle-top twitter bird turns into a spinner (unable to make a screenshot since it disappears too quickly..).

 The aim is to implement the spinner icon as a reusable angular service, with simple interface. All controllers could then call the service like this : 

```javascript
SpinnerService.start();
SpinnerService.stop();
```

### PR DESCRIPTION
**Pull request by zyzo**
Adjust spinner icon to match loklak logo, and change spinner color to loklak default blue.

Fix Issue #419.

### CODE REVIEW

**Comment by mariobehling** [comment]
Do you have a screenshot? Where do you show the spinner now?

**Comment by zyzo** [comment]
The spinner is displayed at the center of the nav bar. When user is not logged in, left loklak logo is not hidden : 
screenshot from 2015-08-12 08 38 56

When user is logged in, center loklak logo is hidden and show spinner icon instead : 
screenshot from 2015-08-12 08 37 34

**Comment by zyzo** [comment]
@aneeshd16 could you check & merge this please ?

**Comment by mariobehling** [comment]
Good work! Very good.

**Pull request merged**
