### PR TITLE
Issue#512, Empty area showing up before report

### LINKED ISSUE #512: Empty areas showing up while generating report
Confusing for the user is, that empty areas still show up while the /report is being generated
* [ ] left hand side shows up until report is available

screenshot from 2015-08-22 10 27 04

* [ ] empty right hand side shows up very briefly and is then hidden. The user wonders "what is it". 
screenshot from 2015-08-19 11 51 49

### PR DESCRIPTION
**Pull request by prasht63**
Fixes #512 

Before report is loaded the empty areas shouldnot show up.

### CODE REVIEW

**Comment by mariobehling** [comment]
Ok, looks good.

**Comment by mariobehling** [comment]
@prasht63 Travis shows that there is a build error. Could you investigate please? I am reverting this until the build error is solved. Cheers.

**Comment by mariobehling** [comment]
Ok, it looks like there is an issue somewhere else. Please check if this build error stays or is just a temp travis glitch. I aborting the revert.

**Comment by prasht63** [comment]
@mariobehling The travis builds are failing due to something else.Maybe isparta is casuing this. .Since not much of change is there in code.So its safe to be merged.

**Pull request merged**
