### PR TITLE
Bfix(#445): Shows months instead of dates for walls with broader time-range

### LINKED ISSUE #445: Wall: Activity Calendar should have months view instead of dates of months
I tried out a wall that starts in January for #GSoC. The activity on the wall shows certain dates. As the period is long, it should rather show months.

See screenshot button right:
screen shot 2015-08-10 at 1 56 59 pm

### PR DESCRIPTION
**Pull request by sopu**
Fixes #445

### CODE REVIEW

**Comment by aneeshd16** [comment]
@sopu is there a screenshot we can look at?

**Comment by sopu** [comment]
@aneeshd16 
Please look at this screenshot.
screenshot from 2016-02-27 11 54 04

**Comment by aneeshd16** [comment]
@sopu will test this tomorrow and revert back.

**Comment by aneeshd16** [comment]
Tested. Good work! Merging.

**Pull request merged**
