### PR TITLE
Dev search v104

### PR DESCRIPTION
**Pull request by fuksi**
Live server: 
http://gofullstack.me:3001/

#483 
- No matter what you do or where you're, there should be only one search box for you (not zero, or two, just one). 
- On loklak.net, if you do a search, i.e. `london` and then type quickly for new search, said `new york`, there will some flashing from the first result to the new result. This won't happen anymore since if one's in progress and another is made, the search (or promise in code) is cancel. 

https://github.com/loklak/loklak_webclient/issues/486#issuecomment-132369037 
- Fix search result not appearing. You can also simply check in console > network, if the trends request comes after search request. Quick link: http://gofullstack.me:3001/search?q=%23vow (you might want to open dev tools before entering the link)

#485 
- When suggestions are shown, clicking outside of it will disable/hide the suggestions
- The other point is solved by the first point of #483 mentioned above. 

https://github.com/loklak/loklak_webclient/issues/424#issuecomment-132331921
- Login page is not shown onload anymore. Still if you're inactive for 7secs, it will show.

### CODE REVIEW

**Comment by sudheesh001** [comment]
All the ones mentioned are working, except that when the suggestions are visible and we click outside, the suggestions do not disable/hide.

screen shot 2015-08-19 at 7 27 25 am

screen shot 2015-08-19 at 7 25 02 am

Clicking outside the suggestions in this case doesn't hide them

**Comment by mariobehling** [comment]
* [ ] Tested "Login page is not shown onload anymore. Still if you're inactive for 7secs, it will show." - Does not show up for me.

* [ ] When I enter a search term and search, then I click on home (loklak cow), the search term shows up in the search bar. This should not happen.

**Comment by fuksi** [comment]
@sudheesh001 Fixed, please check again along with Mario's points above. Nevermind the delay and slow search results, my server is just really slow :)

**Comment by mariobehling** [comment]
If I cancel a search (cause it takes too long) and click back to the home page, it still performs search actions and offers suggestions.

Expected behaviour: A newer search that is performed or clicking to access another page, should cancel the former search.

screenshot from 2015-08-19 12 32 58

**Comment by mariobehling** [comment]
Operators are still hidden with the top behind the top bar.

screenshot from 2015-08-19 12 37 55

**Comment by fuksi** [comment]
http://gofullstack.me:3001/
- The overlay error is definitely fixed. 
- I also made a patch to cancel the search/suggestion when change view. I hope you're able to test it because for some reason my loklak server at gofullstack.me:9000 crashes really often and won't start again until a server restart, which is quite an obstacle to test things.

**Comment by mariobehling** [comment]
Ok, great. Merging it then. Cheers!

**Pull request merged**
