### PR TITLE
Wall creation step2

### PR DESCRIPTION
**Pull request by aneeshd16**
### IMP. Saved walls will not work. You'll need to delete all your saved walls.
Solves #330 and #305 
How to test:
* In step 2, you can add text in "All of these", "Any of these" and "none of these"
* check the query in the network tab if it is according to this: https://github.com/loklak/loklak_webclient/issues/330#issuecomment-122510004

### CODE REVIEW

**Comment by mariobehling** [comment]
Regarding #330 please also add other features coming soon and grey them out.

**Comment by aneeshd16** [comment]
image

Good to merge

**Comment by fuksi** [comment]
There is one unwanted params that makes the result empty: `#london -jee vow /location`. Should `/location` be removed if you're not limiting any location?

**Comment by mariobehling** [comment]
@fuksi Is this finished? If yes, please delete the branch when merging.

**Pull request merged**
