### PR TITLE
Fixes report not showing, and glithc error showing up

### LINKED ISSUE #507: Report not showing up
This bug has been mentioned several times in PR comments etc.: User report does not show up on clicking on "/report"/

Reproduce:
1. Login
2. Click on report
3. User report does not show up
(User report usually shows up if user clicks "Analyze" again, but that is not the expected behaviour.)

Expected Behaviour:
User report shows up after account user clicks "report" right away.
screenshot from 2015-08-20 21 34 15

* [ ] Other unexpected behaviour: There is a glitch message while report generation is performed.

screenshot from 2015-08-20 22 48 30

### PR DESCRIPTION
**Pull request by prasht63**
Fixes #507 
Test : http://loklaktest.cloudapp.net:3000
@mariobehling I am using @fuksi server to show results on my server, since my server's ram has gone out of space.I will fix this.Unfortunately Loklak at @fuksi's server does not have data about your followers-LINK [http://gofullstack.me:9000/api/user.json?callback=angular.callbacks._5&followers=200&screen_name=mariobehling] so you might not see your followers.You can test this with lklknt account.

@aneeshd16 Things to test : 
1. On opening report the report fot you should show without refreshing.
2.The glitch error should not show up unneccesarily
@fuksi I am sorry to put this burden on you server for a while :)

### CODE REVIEW

**Comment by mariobehling** [comment]
Tested with three different accounts. Clicking on report does show up empty reports in each case.
screenshot from 2015-08-21 10 12 52

**Comment by mariobehling** [comment]
As you are also testing this on @fuksi 's server, I am assigning this to him.

**Comment by fuksi** [comment]
It's working on page load. Although, @prasht63, you might want to add some ng-show/hide logic to show the content only when you got the data, since there was a delay/glitch of around 0.5s where the view stays like this.
Screenshot

Other possible fix: The `user-banner-photo` text shows when a banner picture is not available. You can create some logic here to hide it, or just remove the alt value completely.
Another screenshot

**Comment by prasht63** [comment]
@fuksi Please review and merge.Test link same as above. Cheers!

**Comment by prasht63** [comment]
@fuksi any update?

**Comment by fuksi** [comment]
The above are fixed. Merging.

**Pull request merged**
