### PR TITLE
Bfix(#580): Fixes spaces between inline search-filters

### PR DESCRIPTION
**Pull request by sopu**
Earlier buggy view!
afb34792-eb9f-11e5-8acc-a644496200c7

Fixed view as given below!
screenshot from 2016-03-16 18 06 23
![screenshot from 2016-03-16 18 06 21]

### CODE REVIEW

**Comment by sudheesh001** [comment]
Is there something wrong with the screenshots ? Both of them look exactly the same.

**Comment by sopu** [comment]
@sudheesh001:  The two screenshots represent the two different testcases. It fixes issue #580
@aneeshd16: any reason why this was closed?

**Comment by sudheesh001** [comment]
@sopu How is changing `font-size:0px` fixing the problem ? I don't see this problem and am not able to reproduce this.

**Comment by sopu** [comment]
@sudheesh001 please see that this problem occurs with search. ``http://loklak.net/search?q=fossasia`` will reproduce this problem. This occurs due to space between the two li elements. 
Whenever you make anything inline it treats it as text in the paragraph. 
``font-size: 0px;`` basically makes the width of the space ``= 0px``. That's it.

**Comment by sopu** [comment]
Opening this PR as it fixes a small issue! #580

**Comment by sopu** [comment]
Small fix! Merging.

**Pull request merged**
