### PR TITLE
Map tiles can now be attached via loklak

### LINKED ISSUE #97: Cross posts all posts to twitter to loklak server
Large tweets that can be displayed on the `loklak_webclient` app which might include markdown and images have to be also sent to twitter but should redirect the users via a shortener share link that goes along with the tweet post so that the tweet can be viewed on loklak app.

eg. Lorem Ipsum  is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Posted to twitter converted to

Lorem Ipsum .... http://loklak.net/tweet/23716231

The question also is how do we generate the numeric ID information ?
@fuksi @aneeshd16 Could that view on the /tweet/<id> route also be integrated soon. @Orbiter what's your view here ?

### LINKED ISSUE #292: Get location information from browser (share location) and add it to tweet when posting from loklak

### LINKED ISSUE #355: Implement Tweet Attachment "map" and cross post as image to twitter
The attachment typ "map" allows users to attach a map location and show this similar to an image below the tweet. For twitter the idea is to cross post this map as an image.

Related to: https://github.com/loklak/loklak_webclient/issues/94 | https://github.com/loklak/loklak_webclient/issues/292 | https://github.com/loklak/loklak_webclient/issues/93

### LINKED ISSUE #357: Get location info from mobile device and ask user to activate share location
This task is related to https://github.com/loklak/loklak_webclient/issues/292 "Get location information from browser (share location) and add it to tweet when posting from loklak" but it is specifically focusing on mobile devices. There are also subtasks, e.g. automatically identify IP adresses location, cell tower etc. and zoom in the area where the user is currently located, when the user chooses to use map features.

### PR DESCRIPTION
**Pull request by sudheesh001**
Fixes #355 - Attach map tiles and cross post to twitter via loklak.
Fixes #357 - Gets location information and share location via mobiles.
Fixes #292 - Gets location information via share location via browser.
Fixes #97 , #94 - Successfully uploads markdown content.

Currently in this implementation the new editor isn't implemented, the markdown can be tweeted from the same tweet box except that the buttons have to be clicked accordingly. These will be resolved by the next milestone 3.5 and the tracker for that will be #388 

Tests
1. Type in a tweet and click on tweet with map location.
2. Type in a large text content as follows.

```
Lorem Ipsum is simply dummy text of the 
printing and typesetting industry. Lorem Ipsum 
has been the industry's standard dummy text 
ever since the 1500s, when an unknown printer 
took a galley of type and scrambled it to 
make a type specimen book. It has survived 
not only five centuries, but also the leap into
 electronic typesetting, remaining essentially 
unchanged. It was popularised in the 1960s with
 the release of Letraset sheets containing 
Lorem Ipsum passages, and more recently 
with desktop publishing software like Aldus 
PageMaker including versions of Lorem Ipsum.
```

This should be posting a tweet as an image.
3. The application should ask you to share location to which you have to allow.

### CODE REVIEW

**Comment by prasht63** [comment]
There are three problems I am facing
1.I don't know whether the location has been added or not after clicking add location.
2.Tweets are getting posted twice.
3.The box does not close itself after posting the tweet.

**Comment by prasht63** [comment]
Merging #385

**Comment by mariobehling** [comment]
Please provide a link to test this on your server.

**Comment by mariobehling** [comment]
@prasht63 This commit is extremely buggy and unusable. I have no clue why you let that go through.

**Comment by prasht63** [comment]
@mariobehling I tested all the three things listed
1. Type in a tweet and click on tweet with map location.
2. Type in a large text content as follows.

Lorem Ipsum is simply dummy text of the 
printing and typesetting industry. Lorem Ipsum 
has been the industry's standard dummy text 
ever since the 1500s, when an unknown printer 
took a galley of type and scrambled it to 
make a type specimen book. It has survived 
not only five centuries, but also the leap into
 electronic typesetting, remaining essentially 
unchanged. It was popularised in the 1960s with
 the release of Letraset sheets containing 
Lorem Ipsum passages, and more recently 
with desktop publishing software like Aldus 
PageMaker including versions of Lorem Ipsum.
This should be posting a tweet as an image.
3. The application should ask you to share location to which you have to allow.

They were fine on my screen resolution. Should I revert back?

**Comment by mariobehling** [comment]
@prasht63 Is this the currently deployed version on test.loklak.net?

**Comment by prasht63** [comment]
yes

**Comment by prasht63** [comment]
I am reverting it back for now.

**Comment by prasht63** [comment]
@sudheesh001 Please take a look here.

**Comment by mariobehling** [comment]
on test.loklak.net
* [ ] tweet with markdown does not work at all. I also do not know what is the way it is implemented.
* [ ] lots of image issues e.g. i can attach more than 4 images, one image is only uploaded, more
* [ ] map feature does not work. Or I do not get how it is implemented. There is no map to choose. It asks for share location, but it does not show my location.
* [ ] security issues, e.g. tweets are saved after I send them already and they show up again. This even happens across different accounts!

All together this pull request does too many things at one time. On PR = One feature. 

@sudheesh001 This is too much at once. How can we go through all these different parts. It also seems you did not test enough yourself and you put a lot of work on us, which is your work.

**Comment by prasht63** [comment]
I have redeployed test.loklak.net to its previous version.

**Comment by mariobehling** [comment]
Are the problems solved? Where can we test it?

**Pull request merged**
