### PR TITLE
Aneesh/wall

### PR DESCRIPTION
**Pull request by aneeshd16**
## Things to check:
1. Go to /wall/create and enter Event Name, main hashtag, header position and header colour.
2. Start the twitter wall.
3. New tweets are given more priority. Takes around maximum 30 secs for a tweet to show up on wall. (Duration can be shortened)
4. Sidebar is disabled by default. To enable, set `$rootScope.root.sidebarEnabled=true` wherever required. You can set the default value in `js/on_run.js`

### CODE REVIEW

**Comment by fuksi** [comment]
The wall is working, but the order of time is some how reversed.

http://i.imgur.com/ZWQEA6N.png

Some problem with styles:
- The carousel position: http://i.imgur.com/vj9cCD2.png
- Maybe some line-height for the tweet text ;)
- Masonry is working but might be not the way we wanted. Not so important of the moment.

**Comment by aneeshd16** [comment]
How about this? Fixed carousel and set line-height to 120%.
masonry works fine, i think.

**Comment by aneeshd16** [comment]
@fuksi , can we merge?

**Comment by fuksi** [comment]
@aneeshd16 yes of course, please merge and solve conflicts.

Apparently last week when we merged together to my branch, (```aneesh/wall``` to ```dev-search-v200```), after that ```dev-search-v200``` is merged to ```master```. From that point we should have the same base to continue. However, it might be that I forgot to inform you to merge from ```master``` to ```aneesh/wall``` before continuing. (That why you have some conflicts right now, even though the change was made a long time ago). 

In the future, I will inform the related branchs. Or, we can also make it simple by merge only from branch to master, not from branch to branch :)

**Pull request merged**
