### PR TITLE
Wall image upload

### PR DESCRIPTION
**Pull request by aneeshd16**
This PR should solve a few issues:

1. #382. The API can be tested independently by using any REST client like Postman.
2. #376 and #329. Image upload and saving.
3. #332 
4. #330 Clearer design of content area of wall
5. #328

**Needs a `npm install` in both root and oauth-proxy folders**

Link for testing: http://aneesh-ojl02abl.cloudapp.net/wall

### CODE REVIEW

**Comment by mariobehling** [comment]
Where can we test it? Please provide a link to your server to see how things work.

**Comment by aneeshd16** [comment]
Here http://aneesh-ojl02abl.cloudapp.net/wall
I am still working on the icons to display correctly, but apart from that everything else should work.

**Comment by fuksi** [comment]
Checked, quite smooth! Bravo!

**Comment by mariobehling** [comment]
Choose Image does not work on test site for me.

**Comment by aneeshd16** [comment]
Works in Chrome, not in Firefox. Fixes on the way.

**Pull request merged**
