### PR TITLE
Fixes #296 #311

### LINKED ISSUE #296: Implement "show followers/following around the world in percentagewise distribution"
This kind of feature can be viewed at different services e.g. https://tweepsmap.com/Map

screenshot from 2015-07-06 12 39 13

### PR DESCRIPTION
**Pull request by prasht63**
1.Type in a screen name
2.Click on Map Analyze in Reports
3.Hover on a country to see details
image

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a link where we can test this. I am not clear where you added this feature.

**Comment by prasht63** [comment]
@mariobehling you can test it here http://115.99.198.192:3000/report

**Comment by mariobehling** [comment]
Ok, thanks. First thing, I see: I do not understand why you are blocking the screen with an overlay. I have not seen a mockup of this before.

screenshot from 2015-08-04 07 39 34

**Comment by prasht63** [comment]
I had added mockup there on the Issue https://github.com/loklak/loklak_webclient/issues/312#issuecomment-126110251 . This is just to give info what is /report all about and give the users a field to put in input.Do you want it removed?

**Comment by mariobehling** [comment]
We need to stick to the sites design and colors. It does not make sense to give a different user experience on each page.

**Comment by prasht63** [comment]
Ok no problem.You just list out the changes you want in this.I will make them.

**Comment by mariobehling** [comment]
I also do not understand why you analyze loklak_app as a standard. Just choose the user account of the logged in user. This would have been the first thing to implement. An input area needs to be thought though.

Currently, I do not get the analyze screen. I am testing on the current site of test.loklak.net

**Comment by mariobehling** [comment]
1. Follow design on search page 
* [ ] with sidebar left - main area - sidebar right (with the same font, dimensions. Please re-use the css styles!)
* [ ] the bar show followers - following - IoT/data (where the live, accounts, etc. search options are)
screenshot from 2015-08-04 07 58 21

2. Details
* [ ] Add a list of countries, places etc. The scroll over option is not enough. People want to get an overview that they can print out possibly.
* [ ] On scroll down show more influential followers

**Comment by mariobehling** [comment]
* [ ] Please move the percentage color map to loklak.net/map and implement is as on overlay as described here https://github.com/loklak/loklak_webclient/issues/311

**Comment by prasht63** [comment]
@mariobehling The map you see in analyze https://github.com/loklak/loklak_webclient/pull/429#issue-98835173 is not actually a map but a geochart.Its not possible to integrate it with maps as an overlay since leaflet does not support that.
And I think the current design gives us more area to visualise things and its also as per Loklak only.Its the same design we use while creating a wall.I had added a mockup before starting work on it.https://github.com/loklak/loklak_webclient/issues/312

**Comment by mariobehling** [comment]
@prasht63 Firstly thanks for your response, but I am unclear, why it takes a so long to respond. The end of GSoC is ahead and we need to speed up to get to a stable version.

Regarding the design:
a) Please have a detailed look when you compare report and wall. Unfortunately you did not stick to the design details and css of the wall. 
b) The wall UI enables the user to create a wall step by step. Here the design makes sense, cause we have this - a step by step process. So, whenever there is such a process we can use, e.g. also when importing IoT. Otherwise it does not.
c) A report is related to search and it makes very much sense to set it up in the same design.

**Comment by prasht63** [comment]
I will make the changes to the design too.I will add a mockup before doing
that.

**Comment by mariobehling** [comment]
Here is a new mockup idea from me:
screenshot from 2015-08-04 07 58 21

**Comment by mariobehling** [comment]
* [ ] Please also check the spelling of areas e,g. "follwers"

**Comment by prasht63** [comment]
Looks cool! Will implement it by the EOD.

**Comment by prasht63** [comment]
@mariobehling I have made the changes which have been checked above.The screenshot looks like this
image
Can be tested here : http://115.99.198.192:3000/report

**Comment by mariobehling** [comment]
Yesh, it is a start. It seems like you are not using the design of the search though, e.g. main area color and sidebars are different. Profile head picture is missing from the profile on the left as well. I do hope you start to see those things yourself, cause it is tedious and time consuming to point out every small thing.

Cannot login and test:
screenshot from 2015-08-06 07 13 31

**Comment by prasht63** [comment]
@mariobehling Made the changes, you can test it at http://115.99.198.192:3000/report . Please ignore the signup part, my oAuth has some problem

**Comment by prasht63** [comment]
Snapshot if problems in link
image
Will complete it tonight.PR soon.And the profile image missing part and all due to oAuth error.It works fine on local.Those are not issues.

**Comment by mariobehling** [comment]
Ok, let's work on the details.
* [ ] Please use the same CSS styles as on other pages, e.g. the sidebar should use the same as the trend sidebar as front page (I don't know why you center the headings)
* [ ] Get rid of "Analysis" and make the second row in the tables as the heading e.g. country, followers etc.
* [ ] reuse colors from the theme: Instead of dark blue use one of the existing grey colors in the scheme for a heading.
* [ ] follow twitters design and keep the top of the sidebars in one line with the middle main area. See screenshot below:
screenshot from 2015-08-06 23 11 27 
* [ ] design of tables and in particular table column width of different tables must be identical
* [ ] use the same style for "country wise followers" etc. as for the heading of sidebars
* [ ] increase size of round diagrams in middle main area
* [ ] reuse the the page structure of the main page and reuse existing CSS as much as possible, e.g. ensure sidebars match the edges of the top bar on the right and left - like on the loklak start page:
screenshot from 2015-08-06 23 15 38

**Comment by Orbiter** [comment]
why do we have "Trends" two times on the page, once in the left column and secondly in the right column, with same content?

**Comment by mariobehling** [comment]
@Orbiter Agree, but let's discuss this in another issue as it does not relate to this PR.

**Comment by prasht63** [comment]
@mariobehling I will make the required changes, one thing I don't think theres a need for the trends bar here on this page.Its out of place. Don't you think?
Also the heading colour of the headers will also have to be changed for the /search since there also they are grey.Should I change at both the plcaes,since I am using the same css files.

**Comment by mariobehling** [comment]
> I don't think theres a need for the trends bar here on this page.Its out of place. Don't you think?

Keep the area for the trends empty. At a later point we want to see trends of the specific account. What hashtags were mostly used.

> Also the heading colour of the headers will also have to be changed for the /search since there also they are grey.Should I change at both the plcaes,since I am using the same css files.

I do not know how you want to change it. Please fix the above things first and provide mockups of what you mean.

**Comment by mariobehling** [comment]
@prasht63 In regards to the colors for now, please follow this mockup: https://github.com/loklak/loklak_webclient/pull/429#issuecomment-127924677

**Comment by prasht63** [comment]
@mariobehling The design changes have been made
image
I have added a temporary form below user info, it will be removed once we integrate search with it

**Comment by prasht63** [comment]
I am creating a new PR to implement this.Since the changes made here are for analysis and not for percentage wise distribution.Which is the only thing left.

**Comment by mariobehling** [comment]
* [ ] reuse colors from the theme: Instead of dark blue use one of the existing grey colors in the scheme for a heading.
* [ ] Images of accounts are overlapping with other design elements
* [ ] no header profile image in your screenshot

Test link?

**Comment by mariobehling** [comment]
* [ ] Please use the same CSS styles as on other pages, e.g. the sidebar should use the same font and font size as the trend sidebar as front page (I don't know why you center the headings) DO NOT CENTER! Please compare to trend bar and twitter.
* Tables should touch the edge of the main bar or side bars
* Design needs to fit in regards to width - same as account home page

97643496-3d65-11e5-817a-f66ad51f1429

**Comment by mariobehling** [comment]
* [ ] blue main bar should show "report:accountname" e.g. report:mariobehling

**Comment by mariobehling** [comment]
* [ ] increase size of round diagrams in middle main area

**Comment by prasht63** [comment]
"reuse colors from the theme: Instead of dark blue use one of the existing grey colors in the scheme for the table background heading."
 I am not able to get this part. Where am I using dark blue?

**Comment by mariobehling** [comment]
dark blue was previously. The important point is, use "grey".

**Comment by mariobehling** [comment]
FYI
screenshot from 2015-08-08 22 15 36

**Comment by prasht63** [comment]
@aneeshd16 Please review it

**Comment by mariobehling** [comment]
Do you have a test link, please?

**Comment by prasht63** [comment]
http://115.99.198.192:3000/report same as always.
@aneeshd16 
If you find you don't see some countries data etc. Please use a screen_name which is not stored in cache of loklak. A screen_name which has not been used to test before.

**Comment by mariobehling** [comment]
test site does not load. time out.

**Comment by prasht63** [comment]
Its working here, can you test it in incognto

**Comment by mariobehling** [comment]
screenshot from 2015-08-11 17 28 53

**Comment by aneeshd16** [comment]
Site not opening for me too

**Comment by prasht63** [comment]
@mariobehling @aneeshd16 I am looking into it. @aneeshd16 Can you please test it locally.
Test : Go to Report, by defalut it should show your's follower analysis, 
To view anyone else's followers just type in their screen name in input

**Comment by prasht63** [comment]
Can be tested here http://loklaktest.cloudapp.net:3000/report

**Comment by mariobehling** [comment]
* [ ] Design needs to fit in regards to width - same as account home page
* [ ] blue main bar should show "report:accountname" e.g. report:mariobehling
* [ ] for the table heading, please reuse colors from the theme: use an existing grey color

**Comment by mariobehling** [comment]
It does not let me sign in and the analysis does not load to test features completely.

**Comment by prasht63** [comment]
@mariobehling 
1.The design has same sizes of all the three columns.
2.The top bar shows report:@mariobehling
image
image


3.I am using the existing gray color.This is the same colour you see in the topnav links.
About the sign-in error, can you tell me exactly what error you get.Please try in incognito.
About the banner image, that is the image link I am getting from loklak.Maybe scraping error.

**Comment by mariobehling** [comment]
1. It did not look like that when I first tested. Ok now. Thanks.

2. Pay attention to detail, please report:username not report:@username. 

3. It does not look like fitting into the style and there are round edges between the columns. It is tiresome, that you do not see this yourself.

4. Testing incognito should not be possible. I see columns without content. That should not happen. In logged in mode here should be the data of the account holder. Is that the case?

screenshot from 2015-08-12 09 19 59

5. Just log out of your system and try to login. You will see it is not possible. Why do you need me to test this for you? I think you can easily see that error yourself.

screenshot from 2015-08-12 09 23 31

**Comment by mariobehling** [comment]
We need to show some progress on the live system. I am merging this. We can follow up on details in another PR. Cheers.

**Comment by mariobehling** [comment]
Follow up issue here: https://github.com/loklak/loklak_webclient/issues/460

**Pull request merged**
