### PR TITLE
Fixes #13, #5. Search works again!

### LINKED ISSUE #13: TypeError: fs.existsSync is not a function
When I follow the process in README, no page is shown in the browser. The firefox dev tools report
"TypeError: fs.existsSync is not a function"

Steps:
gulp dev
[09:04:41] Using gulpfile ~/git/loklak_webclient/gulpfile.js
[09:04:41] Starting 'clean'...
[09:04:41] Finished 'clean' after 17 ms
[09:04:41] Starting 'dev'...
[09:04:41] Starting 'styles'...
[09:04:41] Starting 'images'...
[09:04:41] Starting 'fonts'...
[09:04:41] Starting 'views'...
[09:04:41] Starting 'browserify'...
[09:04:42] Rebundle...
[09:04:42] Finished 'images' after 93 ms
[09:04:42] Finished 'views' after 162 ms
[09:04:44] Finished 'styles' after 2.07 s
[09:04:44] Finished 'fonts' after 2.04 s
[09:04:47] Finished 'browserify' after 5.15 s
[09:04:47] Starting 'browserSync'...
[09:04:47] Finished 'browserSync' after 58 ms
[09:04:47] Starting 'server'...
[09:04:47] Finished 'server' after 11 ms
[09:04:47] Starting 'watch'...
[09:04:47] Finished 'watch' after 51 ms
[09:04:47] Finished 'dev' after 5.31 s
[BS] Proxying: http://localhost:3000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3001
[BS] External URL: http://192.168.1.56:3001
GET / 200 13.888 ms - 462
GET / 200 6.120 ms - 462
GET /css/main.css 200 11.439 ms - 276914
GET /js/main.js 200 333.890 ms - 3262523

Then the browser opens http://localhost:3001/
it shortly displays "Connected to Browser Sync" and then shows only an empty page
- I open the Firefox JS console and reload
- the console prints out the error "TypeError: fs.existsSync is not a function" in  main.js:35192:8

this is inside node.js. I tested my node version:
$ node --version
v0.12.2

This bug may occur to me because I am a node.js newbie and forget to do something. But then that 'something' should appear in the readme.

### PR DESCRIPTION
**Pull request by aneeshd16**
Constants are stored in configFile.json.
Create your custom settings file by `cp configFile.json
custom_configFile.json
Edit custom_configFile.json to put in custom settings.
I changed constants.js to read this json file, as the fs.readFileSync
used internally by dotenv causes some errors when used with browserify.

### CODE REVIEW

**Comment by Orbiter** [comment]
Thank you!
In contrast to Joergs recommendation to have a commit-review for each change I prefer that you merge your changes yourself (and commit to the main repository in the first place) if your are sure that things are not broken afterwards. If we have a review each time, we lose too much time. Therefore I ask you to check if things are working and then merge this yourself.

Please also consider to change the README documentation as well, as this has changed for the previous version for the configuration option.

**Comment by aneeshd16** [comment]
It works on my machine, but I wanted a code review for the initial commits so that the core functionality isn't broken for anyone in the team. Afterwards, when we begin adding extra features, I will be more comfortable in committing directly to master. :)

**Comment by sudheesh001** [comment]
Works fine for my machine too. r+

**Comment by fuksi** [comment]
While code review can take time, we can simply test the solution and then move forward. r+

**Pull request merged**
