### PR TITLE
Fixes #359 ,adds a drawer, centers the map, removes scroll bars

### LINKED ISSUE #323: Map not centered
There were already some discussions about requests to center the map. As there is no issue to follow up, I am adding one here. Please ensure a centered logic display of the map.

screenshot from 2015-07-09 09 50 07

Compare to a centered map here:

screenshot from 2015-07-07 16 22 27

### LINKED ISSUE #359: Very few Followers displayed / Following missing
screenshot from 2015-07-15 07 59 00

### PR DESCRIPTION
**Pull request by prasht63**
image
Good to merge!
Fixes #359 : Shows followers/following details
Fixes #323 : Map should be centered now
Fixes : #266 : @aneeshd16 Please check if you see scrolls or not.If you see scrolls then don't closee #266.

### CODE REVIEW

**Comment by aneeshd16** [comment]
Looks good, although i would suggest moving the drawer button to the top right and maybe making it a bit bigger.  From a UX perspective, I think some changes need to be made, but I am not sure. @fuksi @sudheesh001

**Comment by mariobehling** [comment]
Where can we test this? It seems a bit clumsy.

**Comment by mariobehling** [comment]
I see that there is a menu item in the middle. I do not understand what these profiles show. Please put up such features on your server, where we can test it.

**Comment by mariobehling** [comment]
#359 : Shows followers/following details
This issue is not about displaying the details on people. This issue is about the fact that lots of followers and following are missing on the personal map.

**Comment by prasht63** [comment]
@mariobehling #359 mostly occurs when followers are plotted at the same place.This feature will show a list of all the followers/following plotted along with their location.Once the loklak starts supporting followers I will use loklak until then we have to rely on Hello.js which is a bit inconsistent, we can do anything about it now.
@aneeshd16 I have moved the drawer control to the top.Please review

**Comment by prasht63** [comment]
@aneeshd16 Can you please review it?

**Comment by mariobehling** [comment]
@prasht63 loklak already supports followers/following. 

Again the question: Where can we test this? Please set it up on your personal web server. I am not sure, the clumsy sidebar is the way to go.

**Comment by aneeshd16** [comment]
image

@prasht63 merging for now

**Pull request merged**
