### PR TITLE
Rework map

### PR DESCRIPTION
**Pull request by fuksi**
A major merge for /map view. Solve #245   

Link to check: http://gofullstack.me:3001/map
Things to check:  
- Followers & followings showing on map
- Clicking on a tweet result in opening a user's pop up
- You can of course click directly on the map as well
- If the user doesn't have location enabled, a notice appears
- If it looks that that the map is not showing enough followers/following, check the area of your country, they're having a party there :)

### CODE REVIEW

**Comment by mariobehling** [comment]
Map is empty.
screenshot from 2015-07-29 11 03 05

**Comment by fuksi** [comment]
Can you refresh the page or go incognito, you might have the old cache. I just tested again on different browers & accounts and it works.

If you're doing this locally, make sure the server is updated and fully configurated.

image

**Comment by mariobehling** [comment]
Tested on Firefox and Chrome with my account and FOSSASIA - not working for me.

screenshot from 2015-07-29 12 23 22

**Comment by fuksi** [comment]
Understood the problem. This will be resolved based on a server's issue: https://github.com/loklak/loklak_server/issues/89. Meanwhile, it for sure will work  locally. @sudheesh001,  can you test this locally?

**Comment by mariobehling** [comment]
I am also missing the overlay button to show/unshow
* followers
* following
* followers tweets

Should we move that for now to the top left of the map maybe?

**Comment by sudheesh001** [comment]
Its good that the https://github.com/loklak/loklak_server/issues/89 was brought up, similar issue would've happened with the tile generations and markdown image attachments.

This patch looks good to merge. Works fine on my localhost.

**Comment by mariobehling** [comment]
@sudheesh001 Did you confirm that the overlay button is there? https://github.com/loklak/loklak_webclient/pull/401#issuecomment-126089866

**Comment by Orbiter** [comment]
>Its good that the https://github.com/loklak/loklak_server/issues/89 was brought up, similar issue would've happened with the tile generations and markdown image attachments.

This is not the first time the loklak_webclient is using a servlet which accepts access from localhost only. There is no issue there, the server works perfectly. You accessed the account.json servlet before and there is not an issue now.

**Comment by sudheesh001** [comment]
No I don't see a overlay button, I see the activity feed on the side in place of the overlay button.

**Comment by fuksi** [comment]
@sudheesh001, it's okay, I'm going to revert this on master, and create a new PR later. We'll need to wait for some changes from the server, and in the mean time I can make more patches as wel.

**Comment by Orbiter** [comment]
please rename the call to account.json into user.json. This new servlet will provide public data and has no access restrictions. The account.json stays protected as it is for localhost only and should also be protected further using Oauthproxy user information details.

**Pull request merged**
