### PR TITLE
Changed button to div for browser compatibility

### PR DESCRIPTION
**Pull request by aneeshd16**
Extremely small change but making a PR for testing:

http://aneesh-ojl02abl.cloudapp.net/wall

Please test if the image can be uploaded

### CODE REVIEW

**Comment by fuksi** [comment]
Succeeded in selecting image. However, wall creation is unsuccesfull. It keeps loading 
image

**Comment by aneeshd16** [comment]
It is uploading the image during that time, you need to wait for a bit. Also see if the console gives anything

**Comment by mariobehling** [comment]
Added an image with 35KB and it does not show up after 10 minutes still. https://github.com/loklak/loklak_webclient/pull/397#issuecomment-125258913

**Comment by aneeshd16** [comment]
its probably because you are not signed in. You need to be signed in to create a wall.

**Comment by mariobehling** [comment]
Still not working. Signed in with my account.
screenshot from 2015-07-28 09 39 38

**Comment by aneeshd16** [comment]
This error happens with only new users. I have updated it, please check again.

**Comment by mariobehling** [comment]
I don't know, what is a new user, but it still does not work for me. Same issue as before.

**Comment by mariobehling** [comment]
@fuksi Does it work for you now?

**Comment by fuksi** [comment]
Still not working for me.

**Comment by aneeshd16** [comment]
@fuksi Please check again
http://aneesh-ojl02abl.cloudapp.net/wall

It was due to loklak_server rejecting requests "not from local". I have manually set the url to `localhost:9000` in my server for now, but we need to find a solution for that too.

**Comment by fuksi** [comment]
Now it's working.

**Comment by Orbiter** [comment]
I just tested this on test.loklak.net and it is not working!

**Comment by mariobehling** [comment]
A wall I set up a few days ago works, but it only shows data from 30 July.
screenshot from 2015-08-02 12 56 03

The same thing on loklak search shows lots of recent results
screenshot from 2015-08-02 12 56 55

**Comment by mariobehling** [comment]
Works for a new wall though for me.

screenshot from 2015-08-02 13 03 20

**Comment by aneeshd16** [comment]
@Orbiter the problem is that you are not able to save your walls?

@mariobehling Could you please share the URL of the wall that is showing old results?

**Comment by mariobehling** [comment]
@aneeshd16 URL of the wall where results are not updating http://test.loklak.net/mariobehling/wall/EkpEwwmc

**Comment by mariobehling** [comment]
As you are creating short URLs now, please just create loklak.net/sAmPleUrL . I do not see the necessity to user mariobehling/wall/shortURL. Facebook does not do it for their pages neither. Just regard a wall as a FB page.

**Comment by aneeshd16** [comment]
image

The wall is querying this URL http://loklak.org/api/search.json?callback=angular.callbacks._0&count=10&q=%23opensource+opensource+since:2015-07-01_05:30+until:2015-08-01_00:30

I checked the saved wall, the param `since` is set to `2015-07-01T00:00:00.000Z` and `until` is set to `2015-07-31T19:00:00.000Z`. This is the reason the wall isn't showing recent results. Please check the parameters you set to create this wall.

**Comment by mariobehling** [comment]
Ah thanks! Stupid mistake. 
I was thinking, if we could also offer people to have an ongoing wall. Just define a start time and an open end time. What do you think?

**Comment by aneeshd16** [comment]
That is totally possible. Just set the `since` parameter and leave the `until` parameter blank, it should work.

**Comment by aneeshd16** [comment]
Regarding short URLs for walls, currently the id of the wall (along with the wall data) is stored as a part of the user's object. I will see if it is possible to store these ids somewhere else so that they can be accessed independent of the user.

**Pull request merged**
