### PR TITLE
 Added a simple map with tweets showing as circles Issue #110

### PR DESCRIPTION
**Pull request by prasht63**
image

### CODE REVIEW

**Comment by prasht63** [comment]
@mariobehling I have closed that Pull Request https://github.com/loklak/loklak_webclient/pull/135 as there were merge conflicts.This one can be merged automatically.

**Comment by aneeshd16** [comment]
@prasht63 I tried the `/map` page. Could you tell me exactly what features i need to test? Thanks.

**Comment by prasht63** [comment]
Thats all for now. 
Thanks

**Comment by sudheesh001** [comment]
@aneeshd16 @prasht63 Map is breaking on deployment,http://loklak.cloudapp.net:3001/map Am I missing something ?

**Comment by prasht63** [comment]
image
Looks fine on mine. Can you send me a screen shot and does console show any errors?

**Pull request merged**
