### PR TITLE
Analysis of Followers Fixes #312

### LINKED ISSUE #312: Implement Regional Origin List View of Followers/Following
An example here is Tweepsmap

screenshot from 2015-07-07 16 45 05

### PR DESCRIPTION
**Pull request by prasht63**
Fixes #312 
How to Test?
Type in the screenname of the user you want to see folowers of.Currenlty its analysing 2000 followers only.Please give it sometime to analyse after clicking.
image

### CODE REVIEW

**Comment by mariobehling** [comment]
Where can we test it? Can you provide a link to your server, please?

**Comment by aneeshd16** [comment]
Nothing happens after waiting
image
This is the log:
image

**Comment by aneeshd16** [comment]
When I opened the page by clicking on the "Report" button in the top bar, I got this
image
I had to reload the page to make the popup appear. Is this expected behaviour?

**Comment by prasht63** [comment]
@aneesh Please re-review, I have updated the code.Also make sure you have the latest loklak_server

**Comment by aneeshd16** [comment]
@prasht63, I looked at the code, noticed that it needs a `topology` object. When I go to http://localhost:9000/api/user.json?screen_name=aneeshd16 my `topology` object is this:
````
"topology" : {
    "followers" : [ ],
    "unfollowing" : [ ],
    "following_count" : 0,
    "followers_count" : 0,
    "unfollowers" : [ ],
    "following" : [ ],
    "unfollowing_count" : 0,
    "unfollowers_count" : 0
  }
````
I am using the latest version of loklak_server.

**Comment by prasht63** [comment]
Add followers=1000 to the url

**Comment by aneeshd16** [comment]
No change. My complete url is `http://localhost:9000/api/user.json?screen_name=aneeshd16&followers=1000`

**Comment by prasht63** [comment]
http://localhost:9000/api/user.json?screen_name=aneeshd16&followers=1000 still doesn't show anything to you?
@aneeshd16 please review after updating.
@sudheesh001 can you review it too.

**Comment by aneeshd16** [comment]
It looks to be a configuration error on my side, please ask @sudheesh001 or @fuksi to review it

**Comment by sudheesh001** [comment]
@prasht63 I have checked, here are a few things to correct, spelling correction for the word `Followers Distribution`

I've checked the requests and i am getting empty responses as follows. Is there anything I need to do before, so that the webclient can take the details from the cache.
```json
angular.callbacks._3({
  "search_metadata" : {
    "count" : "1",
    "client" : "0:0:0:0:0:0:0:1"
  },
  "user" : { },
  "topology" : {
    "following" : [ ],
    "followers" : [ ],
    "unfollowing_count" : 0,
    "unfollowers" : [ ],
    "unfollowers_count" : 0,
    "following_count" : 0,
    "unfollowing" : [ ],
    "followers_count" : 0
  }
});
```

**Comment by prasht63** [comment]
You need to update loklak_server

**Comment by sudheesh001** [comment]
I have the latest server version

**Comment by prasht63** [comment]
http://localhost:9000/api/user.json?screen_name=aneeshd16&followers=1000 does it show anything for you in topology field?

**Comment by sudheesh001** [comment]
Nope, its the same response as above
```
{
  "search_metadata" : {
    "count" : "1",
    "client" : "0:0:0:0:0:0:0:1"
  },
  "user" : { },
  "topology" : {
    "following" : [ ],
    "followers" : [ ],
    "unfollowing_count" : 0,
    "unfollowers" : [ ],
    "unfollowers_count" : 0,
    "following_count" : 0,
    "unfollowing" : [ ],
    "followers_count" : 0
  }
}
```
for the request URL
`http://localhost:9000/api/user.json?screen_name=aneeshd16&followers=1000`

**Comment by prasht63** [comment]
Merging since delaying will create conflicts.

**Pull request merged**
