### PR TITLE
Improved Followers/Following Map

### LINKED ISSUE #313: Implement beautiful design and additional info for followers/following map
This issue is related to https://github.com/loklak/loklak_webclient/issues/232

Step 1: Make a list of useful design features
Step 2: Implement features

Some thoughts about useful features:
* [ ] scroll over effect of pictures on map shows larger image, followers/following info and link "more"
* [x] click on photo shows larger image, followers/following info and latest three tweets

### PR DESCRIPTION
**Pull request by prasht63**
Fixes #313  #232 
Added limits to the number of followers to 1000.
image

### CODE REVIEW

**Comment by prasht63** [comment]
@aneeshd16 dont merge.I am adding one more feature will take 5 mins

**Comment by prasht63** [comment]
@aneeshd16 its good to review.Please review and merge.

**Comment by aneeshd16** [comment]
Looks good :+1: 

Maybe you can remove the scroll-bar at the bottom, and also add a bit of padding to the tweet text
image

**Comment by prasht63** [comment]
ok!

**Comment by prasht63** [comment]
image
Please review.

**Comment by mariobehling** [comment]
@aneeshd16 Please delete this merged branch, if it is not needed anymore.

**Comment by mariobehling** [comment]
@aneeshd16  Please delete the branch after merging.

**Pull request merged**
