### PR TITLE
Solve #9, #11: new route for /eval

### PR DESCRIPTION
**Pull request by fuksi**
Solution for #10 already included the requirement of #9, so I created the rest of the widgets in #11.

Live test here at: http://gofullstack.me:3001/eval

2015-05-04 02_56_41-loklak evaluation

@Orbiter, the aggregated result contains some tweets, in which a mention element can be empty (like the query above). The reason was from the tweet itself, where user used literal ```@``` for no reason.

### CODE REVIEW

**Comment by aneeshd16** [comment]
Can we merge /statistics and /eval into one page? I think that's needed. It looks great! The page is not responsive though. The widgets don't render properly on small screen sizes.

**Comment by sudheesh001** [comment]
@fuksi Looks good so far, can you `soft reset` rebase and push, we're having a merge conflict.

**Comment by Orbiter** [comment]
:)
> It looks great!

YES!

> Can we merge /statistics and /eval into one page?

yes, please merge into one page, call it 'stats' (rename both)

Some points to consider:
- make everything aligned (left border of histogram is left border of first top column and same for the right border)
- make that aligned thing centered
- add a headline and a footer line. The head should be 'Statistics for (search term)'. The footer should be very small: 'Made with loklak. (url to that page)'. The term loklak should be clickable and the url as well.

**Comment by fuksi** [comment]
a newer request is at #26

**Pull request closed without merging**
