### PR TITLE
Fix #575 | Making the User profile box consistent for Report page as home page

### LINKED ISSUE #575: Profile does not show on Reports page
screen shot 2016-03-14 at 12 12 36 pm

### PR DESCRIPTION
**Pull request by akigupta131**
Old
screen shot 2016-03-15 at 1 39 23 pm

v/s

New
screen shot 2016-03-15 at 1 38 38 pm

### CODE REVIEW

**Comment by aneeshd16** [comment]
@akigupta131 This is a wrong approach to solving the problem. The values in the view should come from the analyze controller, and not from the actual values of the logged in user. This is so that the data can be processed before binding it to the view.

**Comment by akigupta131** [comment]
@aneeshd16 In the home view, [value comes from root](https://github.com/loklak/loklak_webclient/blob/master/app/views/home.html#L25) right? 
PS: My bad, if I misunderstood something.

**Comment by sudheesh001** [comment]
A better approach would be to not show the empty profile card until the data is obtained to display the information of the user. I agree with @aneeshd16 that this is not how the values should come in from.

**Comment by akigupta131** [comment]
@aneeshd16 @sudheesh001 I asked earlier too, Does the profile box on reports page show data(Display Picture, Banner Name etc) for the logged in user or the name I am 'creating new report' for?

Earlier, I got answer from Aneesh that it shows data for logged in user. And if that is the case, I am still not getting, why is that approach not right.

**Comment by sudheesh001** [comment]
@akigupta131 It looks like it's definitely providing the results for the currently logged in user and when an explicit query is made it can give the new results for the new user who is queried.

**Comment by akigupta131** [comment]
@aneeshd16 But since I was under impression that data is for logged in user, according to our discussion (Or I might have confused), so I made the solution for logged in user and not for the one for whom query is made. So my solution will not work.

Though some changes can be made to the current main code (not mine) for stabilizing this issue.

**Comment by leonmak** [comment]
closing as #575 postponed due to it being related to loklak_server

**Pull request closed without merging**
