### PR TITLE
Solves #10

### PR DESCRIPTION
**Pull request by aneeshd16**
Created a new route at /statistics
Accept query string and a date range. Display a histogram of tweets.

@Orbiter Kindly review/test this pull. You'll need to a `npm install` before `gulp dev`.
I know you asked me to directly commit. But I am not very sure if this is what is wanted.
Here is a screenshot of the page:
image

### CODE REVIEW

**Comment by Orbiter** [comment]
I love it, great!
I did not ask for a separate page but this is good to test with. Lets keep it there and see how we integrate that with the other stats.

there are some points:
- if you restrict the time frame to only two days, you get a histogram by hours. If you narrow it further, you also get minutes. The scale on the graph should reflect that.
- the timezoneOffset is not used. You must read the value from the browser and send it to the backend as well. Otherwise the narrowed hour-histograms are wrong

**Comment by Orbiter** [comment]
ah, and if possible: please put the get entities into the url to make it possible to tweet such urls!

**Comment by aneeshd16** [comment]
3a8a0b461d9b388480962509d5f9e4ebce4d6bad adds more control over date/time selection and also adds timezoneOffset.
Now trying to get them from url params.

**Comment by fuksi** [comment]
I got errors with morris.js after pulling the new merge, does anyone have the same problem?

screen shot 2015-05-03 at 19 45 02

**Comment by aneeshd16** [comment]
@fuksi okay, i can replicate that. happens when there are no tweets in the given period. You can try searching for a different term/time range. Till then i'll fix it so that it displays a "no tweets found" or similar error message.

**Comment by smokingwheels** [comment]
@aneeshd16 I have some zeros in my server to test if you wish.
http://swlok.mooo.com/api/search.json?q=youtube%20since:2015-04-01_17:10%20until:2015-05-31_18:20&source=cache&count=0&fields=created_at,screen_name,mentions,hashtags&limit=6&timezoneOffset=-120

**Comment by aneeshd16** [comment]
@smokingwheels, Thanks! But the error occurs when `created_at={}` Zeros are okay!

**Pull request merged**
