### PR TITLE
#95 Geolocations and image uploads methods

### PR DESCRIPTION
**Pull request by sudheesh001**
- [x] After signup click on the tweet button and add image, type a tweet message and press Tweet.
- [x] No more lexer errors about #294 signupModal

### CODE REVIEW

**Comment by prasht63** [comment]
What all i have to test?
I tried clicking on location and adding photo nothing happened

**Comment by sudheesh001** [comment]
Its not yet complete, the problem i am facing is an CORS error on fetching the image tile from localhost and the other issue is that the file comes up as `undefined` when uploading it

**Comment by Orbiter** [comment]
I don't understand the CORS problem - I believe this is only enfored for AJAX request to json sources AND if the source is from a different domain than the loading code. Both is not the case.

**Comment by sudheesh001** [comment]
@Orbiter this is what the console says
```
XMLHttpRequest cannot load http://localhost:9000/vis/map.png?text=Test&mlat=17.4547158&mlon=78.3695934&zoom=13&width=512&height=256. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

**Comment by julianfox** [comment]
Hey, i already has this issue on few projects, the requested resource have to send a Access-Control-Allow-Origin header.

Like explain in this doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

For fixe it, the backend have to send a Access-Control-Allow-Origin header that give access for the front-end side.

I hope that can help !

**Comment by prasht63** [comment]
Can you tell me how to test? I tried adding location nothing happened.Same with Add photo

**Comment by prasht63** [comment]
XMLHttpRequest cannot load http://localhost:9000/vis/map.png?text=Test&mlat=12.926469299999999&mlon=77.6700477&zoom=13&width=512&height=256. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by prasht63** [comment]
I updated loklak_server and tried.Same error.

**Comment by sudheesh001** [comment]
@prasht63 I updated the details as list items here https://github.com/loklak/loklak_webclient/pull/276#issue-92967276

**Comment by prasht63** [comment]
I get a over capacity error on posting a image.Size of file is 100kb.

**Comment by sudheesh001** [comment]
@prasht63 What is the exact error message ?

**Comment by sudheesh001** [comment]
@prasht63 This looks like the culprit https://github.com/loklak/loklak_webclient/commit/b8411163379c874df2bfaa40067d5b999200ef29#diff-e88a07016d81fa0cd124501e02ae0327R14 but definitely even changing it to 2048 isn't solving the problem, any view @fuksi ?

**Comment by sudheesh001** [comment]
@prasht63 This looks like the culprit https://github.com/loklak/loklak_webclient/commit/b8411163379c874df2bfaa40067d5b999200ef29#diff-e88a07016d81fa0cd124501e02ae0327R14 but definitely even changing it to 2048 isn't solving the problem, any view @fuksi ?

**Comment by prasht63** [comment]
Cool! I am able to post images now.And no error regarding lexer.Merging

**Comment by mariobehling** [comment]
@sudheesh001 Please document the way this has been implemented on the readme.md.

**Comment by sudheesh001** [comment]
@mariobehling I'll do that

**Pull request merged**
