### PR TITLE
Adapt message view popup modal to #449 design

### PR DESCRIPTION
**Pull request by zyzo**
With raw json appended as rich text of data source, more information about the data could be displayed, & can be configured by each source type.

Fix proposed design for map & file popup in #449.

TODO : 

- [x] Integrate the new popup into map view
- [x] Add share button
- [x] Implement deep field traversal so the popup can access more interesting data from raw json. 

Server side correspondance : https://github.com/loklak/loklak_server/pull/117

### CODE REVIEW

**Comment by mariobehling** [comment]
Please post screenshots for new features. It is really a pity that you did not achieve to set up the project on a test server.

**Comment by zyzo** [comment]
@mariobehling screenshot in file view mode : 
screenshot from 2015-08-20 16 04 17

I was able to fix connection problem of my test server http://45.55.221.77:3001/ this morning, however I encountered another problem with ddos limit. Will try to fix the problem asap.

**Comment by mariobehling** [comment]
Ok, this is a big improvement. I see, that you have an importer and sharer. The idea is, that importer = sharer. 

Question that comes up following this way, what happens if the importer deletes the file or changes it? In this case the file stays in the database, but the "link" gets deleted from the account. @Orbiter mentioned a while ago that he created fields to ensure this feature.

**Comment by zyzo** [comment]
> The idea is, that importer = sharer.

So I separated the notion of `importer` and `sharer` to distinguish the user who adds the connection via the add overlay, and the users who click `Share`. `Importer` is really just the 1st sharer.

A problem with `importer = sharer` is, who is allow to change the data (harvesting frequency, public/private status, etc..) ? My suggestion is, in the db we still make the distinction, but on loklak_client I can add the importer to the list of common sharers.

> what happens if the importer deletes the file or changes it? In this case the file stays in the database, but the "link" gets deleted from the account.

Currently, my idea is, if a sharer `unshared` it, his/her username is simply removed from the list of sharers. When the importer clicks on Delete, there is a field [EntryStatus](https://github.com/loklak/loklak_server/issues/67) that will change from `ACTIVE` to `DELETED` and will not be searchable by common users. Relevant here https://github.com/loklak/loklak_server/issues/67

**Comment by mariobehling** [comment]
> A problem with importer = sharer is, who is allow to change the data (harvesting frequency, public/private status, etc..) ?

Yes, that is a good question:
* [ ] harvesting frequency - I think we can let every user choose the frequency and harvest it according to the user who sets the highest frequency. And we display instead of "Check for updates every" - "Check for updates at least every"
*  [ ] Public/Private: We only need this option, if we require authentication from a user. Public - everything that is public on the Internet should be public. Private - this option can only be used when we add apps, that require user specific authentication. Prashant is working on adding apps that require authentication. If a user shares data that requires authentication, the user should stay in control of the data. That means, we can temporally keep the data in loklak, but if the user deletes it from his/her account, others should neither be able to see it. As this is more complex, I am opening a separate issue for this feature.
* [ ] Statuses: What is the specific info here? Statuses should be defined in the file, right? The user does not change anything here, or does s/he?

**Comment by zyzo** [comment]
Thanks, this should be enough to merge the 2 concepts. Currently when a user adds a data that already exists, she/he will be prompted with a message `1 source known, 0 new source added`. I will change it to `This source is already added. Do you want to share it ?`.

> Statuses: What is the specific info here? Statuses should be defined in the file, right? The user does not change anything here, or does s/he?

I meant privacy status when I said `public/private status`. Sorry for any confusion.

**Comment by zyzo** [comment]
Test server is UP http://45.55.221.77:3001/. @mariobehling Could you please review & merge this ? The feature only works with https://github.com/loklak/loklak_server/pull/117 therefore the server pull needs to be merged & deployed equally.

**Comment by mariobehling** [comment]
Looks like server crashed when I tried to login.

screenshot from 2015-08-24 06 23 59

**Comment by zyzo** [comment]
@mariobehling the server is up again, sorry for the downtime http://45.55.221.77:3001/connect. 

@fuksi thanks for your help. The problem seems to be the way console log is redirected. When I do `gulp live &` and disconnect from the ssh tunnel, twitter login will fail. `gulp live 1> log.txt 2>log.txt` did the trick. Just thought you should know!

**Comment by mariobehling** [comment]
* [ ] Map does not display
screenshot from 2015-08-25 13 07 12

* [ ] Data shared by other user's should not show up in "My Data" of data sources - except if I shared it - and therefore show it in "My Data"
screenshot from 2015-08-25 13 08 40

* [ ] How can it be that data that is shared by "0 people" is in the system?
screenshot from 2015-08-25 13 07 51

* [ ] Understanding the difference between showing data in everyones account and public data a) public data can be searched and found in search results b) private data does not appear in search results and other public pages

**Comment by zyzo** [comment]
>  Understanding the difference between showing data in everyones account and public data a) public data can be searched and found in search results b) private data does not appear in search results and other public pages

Regarding private data that aren't searchable, currently there is something like that implemented for loklak messages. There is currently a private/public field for ImportProfileEntry, but not for MessageEntry. I suggest the same field to be added to MessageEntry. But as MessageEntry is the core class of loklak_server that interacts with lots of other parts I think it would be wise to wait for @Orbiter's inputs when he returns.

**Comment by mariobehling** [comment]
@zyzo Please outline your ideas for implementation and the relevant questions and write an email to @Orbiter.

**Comment by mariobehling** [comment]
@zyzo:
> The use case of private data is different from public data in several ways : the user that imports the data, is in control of the data. That means only that user is allowed to update/delete, allow/prohibit other people from seeing the data. In order to implement these criterias, I believe following code additions are needed :
1. Add new privacy_status field to MessageEntry, that could be PUBLIC or PRIVATE (PrivacyStatus class is implemented in ImportProfileEntry)
2. Add visibility boolean field value to MessageEntry. For public data this field is of no use. For private data (privacy_status == PRIVATE), if visibility is set to true, other people can search for the data. Otherwise, only the owner can see the data. (this field can also be created as an enum, for extensibility reason).
3. Change the message search method in QueryEntry to match these constraints.
As you have a more global view of loklak_server codebase, do you think these changes are appropriate ? 

@Orbiter:
> I don't know why we need that, but the proposed solution is not flexible enough. This should be solved using a mandant model where each mandant can apply their access right. This enables that once created record can change their access right without actually changing the content of the records itself. The requiremennts would be simple:
- add a field 'collection' with empty default value
- each mandat has a name which is written to the mandant value
- each mandant can write an access right attribute to a new data structure. This should define access rights to groups 'all', 'group' and 'user' (like in unix groups)
- each user of the search interface must be identified to be member of none, one or several mandants. This must be trannslated to a filter query to the collection field.

**Comment by prasht63** [comment]
@zyzo let me know when this is ready for reviewing. Cheers!

**Comment by zyzo** [comment]
@prasht63 Sure, I just deployed latest bug fixes. Please check if these features work well : 
- Add connections from all source types 
screenshot from 2015-08-28 15 19 44
  - [ ] FOSSASIA API https://github.com/fossasia/directory.api.fossasia.net/blob/master/directory.json
  - [ ] Freifunk routers https://github.com/zyzo/ff2ll/blob/master/urls.json (except freifunk nodes links)       
  - [ ] Geojson
- [ ] File view
- [ ] Map view
screenshot from 2015-08-28 14 42 55
- [ ] Edit & Unsubscribe sources

Please note that file view & map view might be disabled for some sources that contain lots of data. This problem will be fixed with proposal https://github.com/loklak/loklak_server/issues/120. 

@mariobehling I moved the discussion about public/private data to #503 and the issue will be addressed in a separate PR.

**Comment by mariobehling** [comment]
Travis fails due to limits testing on container infrastructure. I am merging this. Minor bugs can be handled in future issues.

**Pull request merged**
