### PR TITLE
Fixes #355 Map tiles can now be attached.

### LINKED ISSUE #355: Implement Tweet Attachment "map" and cross post as image to twitter
The attachment typ "map" allows users to attach a map location and show this similar to an image below the tweet. For twitter the idea is to cross post this map as an image.

Related to: https://github.com/loklak/loklak_webclient/issues/94 | https://github.com/loklak/loklak_webclient/issues/292 | https://github.com/loklak/loklak_webclient/issues/93

### PR DESCRIPTION
**Pull request by sudheesh001**
Steps to reproduce
1. Type in the tweet you want 
2. Click on Attach location which also does the post operation of the tweet currently.

### CODE REVIEW

**Comment by mariobehling** [comment]
Do you have screenshots? Please give us a link to a test system.

**Comment by sudheesh001** [comment]
@mariobehling There has been a change with my campus proxy networks and its blocking ssh hence I am unable to set it up on my test machine. I request @prasht63 to review this on local and merge.

By then i'll get to the university IT Admin and get SSH priviliges unblocked

**Comment by prasht63** [comment]
Works great! Can you add a spinner while the Tweet is being posted.For now it just goes dead for 3-4 seconds then closes the tweet modal.Also a confirmation bubble or something would be nice. The core functionality is working! :+1:

**Comment by sudheesh001** [comment]
@prasht63 There is a spinner on the top but I guess it needs to be brought to the foreground, Thanks for the feedback, i'll check this up

**Comment by mariobehling** [comment]
@sudheesh001 There are tons of services on the net - Heroku, Digital Ocean, Amazon, Bluemix... - where you can set it up and test it. Please do not make excuses. Also, I do not know why you cannot add screenshots here. I think, we have asked you many times to provide screenshots for different issues and PRs. I am very confused by your continuous excuses.

**Comment by prasht63** [comment]
@sudheesh001 let me know when this is ready for review

**Comment by sudheesh001** [comment]
Map attachment button can be clicked
screen shot 2015-08-03 at 8 33 16 am
The map tile is the complete area, in the image due to repeated requests I made, the grey tiles have started to appear. One point can be chosen on the map
screen shot 2015-08-03 at 8 35 40 am

**Comment by mariobehling** [comment]
Where can we test this?
* [ ] Please provide a link to your test system. 
Add photo, location, map are in different colors, why?
* [ ] Change "Get Location" and "Attach Map" to Grey
* [ ] Show the Get Location function

**Comment by mariobehling** [comment]
How can a user set the marker? Please offer a link to a test site.

**Comment by sudheesh001** [comment]
Get Location is used to retrieve the city name from where the user is posting this particular information.
Attach Map is the button that has to be clicked so that the user can attach the map, One can attach the marker on the map by clicking on the location where the user wants the map to be put up.

I've also integrated the markdown area where the markdown attachments (large text) can be pasted so that that information can be sent to loklak to generate an image.

This needs a little more work, but here's the progress so far.

screen shot 2015-08-03 at 4 27 14 pm

Using the markdown content after clicking on Attach Text
screen shot 2015-08-03 at 4 27 38 pm

Markdown content typed into the markdown editor
screen shot 2015-08-03 at 4 29 59 pm

Rendered markdown in View Mode
screen shot 2015-08-03 at 4 30 07 pm

**Comment by mariobehling** [comment]
Test link, please.

**Comment by sudheesh001** [comment]
You can test this at http://loklak.cloudapp.net:3001/

**Comment by prasht63** [comment]
@sudheesh001 1.Please clear out all the fields once the Tweet has been so that I can post another tweet without having to reload.
2.Once I choose the Attach map option,I can't use Attach photo, so just disable or hide it.

**Comment by mariobehling** [comment]
Lots of details are still to be done and lots of it was mentioned before. I think you should see those things yourself. A developer is the first person who should test his own development. Some points:
* [ ] Use latest master for testing your code
* [ ] Get location does not work after allowing to share and I cannot enter my location manually
* [ ] Overlay compose area it is very large. Please decrease the width to what is possible
* [ ] Grey out functions when they become unavailable, e.g. after creating a rich text attachment, photos cannot be uploaded anymore
* [ ] At the moment only the upload of one item is supported. Why is it possible to add more photos and attachments in your interface?

**Comment by sudheesh001** [comment]
@prasht63 The tweets and information now gets cleared after posting reducing that security risk. Also once an option like Attach map / markdown is chosen , the add photo automatically makes itself unavailable.

>Get location does not work after allowing to share and I cannot enter my location manually

@mariobehling Yes, I understand that this isn't the exact procedure, the `getLocationSuggestions()` was implemented in the advanced-search filter by Phuc, Can we have another issue for this instead of blocking it with the main functionality being merged, since the services and controllers are written seperately for that, I would like to minimize duplication of the source code and need to get a more efficient way to doing the location suggestions as we type in the tweet view.

**Comment by mariobehling** [comment]
@sudheesh001 Yes, please follow up about get location in a separate issue.

**Comment by prasht63** [comment]
Serves the basic functionality, did not find any bug while testing.So merging.

**Pull request merged**
