### PR TITLE
Feature/wall statistics view

### PR DESCRIPTION
**Pull request by aneeshd16**
1. Statistics now shows up in the wall
2. Images in linear and centre of attraction layouts render correctly.

This should solve #73 and #156

### CODE REVIEW

**Comment by fuksi** [comment]
This is delayed until master is clean.

**Comment by fuksi** [comment]
This merge has conflicts, those are deeply related to wall feature that I can't really resolve. 
@prasht63, @aneeshd16 please discuss further ab this PR.

**Comment by mariobehling** [comment]
@prasht63 @aneeshd16 What is the outcome here?

**Comment by sudheesh001** [comment]
We need to get this up and running quick, I'll look into these, cherry pick them and resolve the conflict today after dinner.

**Comment by aneeshd16** [comment]
@prasht63 , lets resolve this asap

**Comment by fuksi** [comment]
Features mentioned here are working. But @prasht63 wall with map is not working anymore.

**Comment by prasht63** [comment]
@fuksi I am reviewing it right now.Let me see

**Comment by prasht63** [comment]
@aneeshd16 any reason the map is not showing up? I see this 
image

**Comment by aneeshd16** [comment]
@prasht63 @fuksi fixed.

**Comment by fuksi** [comment]
@aneeshd16, @prasht63 
- Maps and statistics at the same time does not work.  
image

**Comment by aneeshd16** [comment]
@fuksi, maps isn't working at all. Prashant and I are working on this, hopefully this will be fixed before EOD.

**Pull request merged**
