### PR TITLE
Bfix(#534): Fixes sidebar and topbar edge positioning issue

### PR DESCRIPTION
**Pull request by sopu**

### CODE REVIEW

**Comment by sopu** [comment]
screenshot from 2016-03-15 17 52 08

**Comment by sopu** [comment]
Screenshot after right-bar pie-chart position fix. 
screenshot from 2016-03-15 18 04 48

**Comment by sudheesh001** [comment]
Can you add a small spacing between the left search text box and the button and if possible convert that button to be having elliptic curves similar to the text box!

**Comment by sopu** [comment]
@sudheesh001 refer to this #571. 
"Adding elliptic curves similar to text box" - Won't it create inconsistencies in button designs?

**Comment by sudheesh001** [comment]
@sopu I am not finding any changes in before and after views. Can you mention what `exactly` i should be looking for ?

**Comment by sopu** [comment]
capture
@sudheesh001 please see the screenshot ^. This is the earlier view.

**Pull request merged**
